### ISSUE TITLE
Band information in Landsat8 example is not as specified

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#105]
I think the Landsat example at https://github.com/radiantearth/stac-spec/blob/master/json-spec/examples/landsat8-sample.json has some errors, which I struggled with during my work on #81.

- Why is "eo:bands" part of the assets? I assume it's an error and should be moved either one level up or into properties.
- The landsat example uses `fwhm` instead of `full_width_half_max`. ;)

**Comment by cholmes** [comment]
Apologies for that. Someone else pointed out something similar a couple days ago. I'll try to cut a 0.4.1 release with this asap.

**Comment by cholmes** [comment]
Ok, I think this is fixed. Moved bands out, I just did an example link to collections, and updated the readme to point at the example in extensions - https://github.com/radiantearth/stac-spec/tree/master/extensions/examples So that also moves out the fwhm stuff.

Thanks @m-mohr for the feedback! We're excited to collaborate on the 'collection' level stuff. Sorry we didn't get a ton fleshed out for this release, but I'm sure it will continue to evolve, and we're also happy to take queues from you.

**Comment by m-mohr** [comment]
@cholmes Thanks!

Additionally, I think you should have a look at https://github.com/radiantearth/stac-spec/blob/master/extensions/examples/landsat8-merged.json . There is also the eo:bands in the wrong place. Sorry, I forget to mention that in the initial issue text. The files are now basically the same, maybe the merged example can be removed at all?

Take your time with the collections, I am happy to contribute as much as I can. Have some initial things posted in #81.

**Comment by cholmes** [comment]
Well the idea of the 'merged' was that it showed the combination of the landsat8-sample.json and the L1T-collection.json in one. Demonstrating that what 'complete' Item record could look like, pulling in the 'collection' fields in to the smaller Item file. So it's like the full representation of a record, if a client expanded things out.

Though I do now realize that it doesn't use full_width_half_max so that should be updated.

**Comment by m-mohr** [comment]
@cholmes Okay, thanks for the clarification, I understand that now. Still, there some to be some inconsistencies (or I don't understand it correctly):

- eo:bands is also still part of assets in the merged example.
- Why is eo:bands not part of properties in the collection?
- Why does landsat8-sample still duplicate provider, license, eo:gsd and other fields that already exist in the collection?
- Why is collection_name and collection_description missing in the merged example?

(Another small suggestion: I'd run all examples through a JSON formatter, e.g. https://jsonformatter.curiousconcept.com/, so that they are all following the same formatting style. Makes it easier to compare and read them.)

**Comment by m-mohr** [comment]
Hi @matthewhanson , 

thanks for answering all my questions. I think I finally got the whole idea. I'll update #81 accordingly today and maybe open one or two new issues.
