### ISSUE TITLE
Spatial resolution as common metadata?

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#1196]
In a recent discussion about a landcover product, we struggled with gsd again.

> We've been using `raster:bands -> spatial_resolution` instead of `gsd` for pixel size. From our reading of the spec, GSD applies to the sensor resolution, while `raster:bands -> spatial_resolution` seems more appropriate for a land cover product.

> Yeah, while I agree I hate that we don't have a way to globally specify the spatial resolution because you can't easily search for the resolution then and also you can't summarize it easily. That's also the reason I mis-used gsd, because I found it has advantages that IMHO outhweigh the "conflict", but ideally we would have spatial_resolution in common metadata...

Thoughts? I feel like it's useful to have an easy way to search across collections for spatial resolution without needing to dig into bands. Also, makes summarizing easier as you don't necessarily need to implement Item Asset Definitions and look into specific items. 

Origin: https://github.com/stactools-packages/esa-cci-lc/issues/7

**Comment by emmanuelmathot** [comment]
IMO, the problem is in the multiple definitions of `gsd`. One given [here](https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#gsd) is not inline with the one given [here](https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#additional-fields-for-assets) ? Personally, we apply the latter one and use `gsd` both at item and assets level:
> For example, gsd defined for an Item represents the best Ground Sample Distance (resolution) for the data within the Item.  However, some assets may be lower resolution and thus have a higher gsd.

I think the confusion resides in the former definition that tries to describe the instrument and not the item. The rule of thumb should always be that we describe metadata of a product item, not the procedure that led to it.

**Comment by m-mohr** [comment]
This will likely be solved with Bands RFC as then you can just use `raster:spatial_resolution`.
