### ISSUE TITLE
Define ItemCollection in stac-spec

### ISSUE THREAD

**Issue by philvarner** [radiantearth/stac-spec#1251]
ItemCollection was removed in 

- #810 

so that it now only existing in the STAC API specification. The reason for this was that it is not connected to the other core types (Catalog, Collection, and Item). However, there are use cases for this related to GeoParquet, so it would be useful to have a "standalone" definition of ItemCollection outside of STAC API.

**Comment by matthewhanson** [comment]
Discussed in sprint - decided we do not want ItemCollection to be it's own entity in the STAC spec (because then it would require stac_version). Instead the problem is one of visibility and documentation.
Need to link to ItemCollection (and CollectionCollection) from stac-spec and make it clear to users the format of those arrays.  
Also link to from website.

**Comment by emmanuelmathot** [comment]
Where is the CollectionCollection definition?I only find this reference: https://github.com/radiantearth/stac-api-spec/tree/main/ogcapi-features#collections-collections
