### ISSUE TITLE
Metadata should include a "constellation" property

### ISSUE THREAD

**Issue by hgs-trutherford** [radiantearth/stac-spec#141]
In the spec, it uses sentinel-2A as an example under eo:platform. Users don't usually care whether it is 2A or 2B, but they would be interested in getting a sentinel-2 image.

including for discussion
@hgs-msmith

**Comment by m-mohr** [comment]
I randomly discussed this with a colleague and talked about the same issue. 
At the moment users usually don't care about A or B, but with C and D coming (for sentinel-1) and eventually a shutdown or defect of any of the satellites in the future, it could get interesting to users.
Therefore it should be possible to either search for groups or a specific satellite. 

Is this example how you thought about it @hgs-trutherford?
constellation: "sentinel-2"
platform: "sentinel-2A"

A question that arises is: How to group correctly? Do we need something like a look-up table for that? Otherwise someone could just use "sentinel" as constellation.

**Comment by hgs-trutherford** [comment]
I was thinking sentinel-2, we are planning on storing both sentinel-1 and sentinel-2 and they are pretty different, so I don't think I would want to clump them together.

The one that has been more interesting to me is planet data. The planetscope "constellation" has both 3 band and 4 band data. So I'm struggling with constellation being more of an organizational concept and doesn't necessarily represent capabilities. But I think that is right, if you want a 4 band product, you should probably search for a center_wavelength band.

**Comment by fredliporace** [comment]
Form the user's perspective my view is that the grouping should be made considering sensor and platform orbit characteristics. For instance, MSI with S2A/B, MODIS with Aqua/Terra (*), RapidEye should be grouped since they have same (or very similar) sensors and platform orbit.

(*) Aqua/Terra ascending/descending node may be a significant difference for some applications.

**Comment by jeffnaus** [comment]
I'll add constellation to the EO extension in an upcoming PR.

**Comment by matthewhanson** [comment]
There's also an "eo:instrument" field, which is similar (but not exactly) to how you are talking about constellation here. The reason why users want to use Sentinel-2A and 2B together is because the sensors are the same (or almost the same, there's very slight differences in a couple of the spectral bands).

The Aqua and Terra sats can be thought of a constellation because they carry the same instrument (MODIS).

Landsats L5, L7, and L8 sats are not a constellation because they carry different instruments, although maybe L4 and L5 could be a constellation because they do both have the same sensor (TM).

Planet imagery is definitely a constellation, but I think that might be two constellations, separated by instrument.

Thus in most cases constellations are just the same instrument. At the moment I can't think of a use case where you would want a constellation made up of different instruments. However, as pointed out above even though Sentinel 2A and 2B are technically the same instrument (MSI), they are in fact slightly different. In sat-api I grouped them together, as it's only minimal differences in the spectral characteristics and I don't think worth having separate profiles.

So on one hand I think eo:constellation is redundant with eo:instrument. On the other hand I can envision some future case where the sensors have slightly different characteristics but it makes sense to group them together.

**Comment by fredliporace** [comment]
Note that it is possible for the same instrument to generate different products depending on the platform characteristics. This will happen for the WFI camera which current flies in CBERS-4, it will also fly in Amazonia-1 satellite but since the orbit is different the product GSD will be distinct. If Amazonia-2 uses the same camera then WFI on Amazonia-1/2 could be viewed as a constellation, not including WFI in CBERS-4.

**Comment by cholmes** [comment]
Closing this, as it got merged. They're both optional fields - would be good to explain how we see them as different. @jeffnaus - maybe you can explain difference between constellation and instrument? 

Seems like constellation may just give flexibility to define a grouping by something other than the instrument? 

If someone wants to reopen and argue for removing constellation then go for it - I had thought it was a bit more settled.
