### ISSUE TITLE
Not clear where to put fields in JSON (properties vs. top-level)

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#143]
Maybe I missed something in the written documentation (not speaking about the schemas), but is somewhere mentioned how to organize the fields? Some are placed in the GeoJSON-properties, some are placed outside (top-level). Non-objects seem to be in the properties and all others are placed outside, but that is not really documented anywhere?! For example, eo:bands seems to be placed outside of the properties, all others are placed inside. That is lacking documentation and could lead to differing implementations.

Additionally, I still don't see a strong reason why objects like eo:bands should not be in the properties, but be placed as a top-level element.

**Comment by cholmes** [comment]
I'll try to add some clarification on this to the spec.

The main answer is that everything in properties should be 'flat', as pretty much no standard GIS (web or desktop) really does anything great with nested JSON. So the goal is that the properties get displayed by any standard GeoJSON reader. 

If there was a standard 'links' convention we'd adopt it. But since it and assets needed to be nested objects we felt they should be outside. 

Bands is similar I think. Basically since a generic GeoJSON reader won't understand the nesting we felt we should put them explicitly outside, so that a STAC aware reader could make use of them. Though EO bands I do see as something that should be referenced, not included in every Item...

**Comment by m-mohr** [comment]
I remember that the "ancient" Desktop GIS were limited with their properties, yes. Moving them outside just hides those information completely from those users, so they would have no clue about bands as it's not in the properties, am I right on this?

**Comment by matthewhanson** [comment]
I think that's a good rule. Properties should be flat and thus searchable. Elements outside are going to be referenced by client code for processing, etc.. but don't really contain fields that are useful to search on.

eo:bands would usually appear in a Dataset definition, if used.

**Comment by m-mohr** [comment]
Gave it a first shot in #202, especially in the Properties Object.
@cholmes Do you think this is enough explanation or do you want to improve it? Otherwise issue can be closed.
