### ISSUE TITLE
Update implementation list

### ISSUE THREAD

**Issue by metasim** [radiantearth/stac-spec#158]
A number of implementations are popping up (e.g. DevelopmentSeed's sat-util, Element 84's cmr). It would be helpful to have a catalog of these listed in the `sat-api` section.

**Comment by cholmes** [comment]
We have https://github.com/radiantearth/stac-spec/blob/master/implementations.md which is an obvious place, but is a bit out of date. It should likely include what version of STAC the implementations are at.

A bit nicer is https://github.com/radiantearth/stac-spec/blob/master/static-catalog/examples.md which we did since we removed the static catalog 'examples'. But the implementations should be merged in, and examples should maybe just refer to the github repos? Not sure, it is useful to see the real world examples - but maybe it just says to check the implementations. Could also make sense to do one small catalog / dataset example.

**Comment by metasim** [comment]
Both are awesome for us.... the static more pertinent to what we want to do right now. Just having a destination is a great start. Close this?

**Comment by cholmes** [comment]
I'd like to leave it open as a reminder to update before the next release...

**Comment by m-mohr** [comment]
I made a PR (#238) to merge and update the implementations/examples.

**Comment by m-mohr** [comment]
@cholmes , do you still want to update this, right? Or was my merge already all to do? Then this could be closed.

**Comment by cholmes** [comment]
Ideally we have this updated with links to some actual 0.6.0 implementations that are made after the release candidate. And we should be sure to specify that the other implementations are still 0.5.0 (but likely updating soon)

**Comment by cholmes** [comment]
Going to close this, as I'd like to move implementations to http://stacspec.org, so they're not like tied to releases, etc.
