### ISSUE TITLE
consideration of OpenSearch EO extensions

### ISSUE THREAD

**Issue by tomkralidis** [radiantearth/stac-spec#16]
Hi all: wondering if there has been any consideration on the [OGC OpenSearch Extension for Earth Observation](http://docs.opengeospatial.org/is/13-026r8/13-026r8.html#figure_1) Implementation Standard?  Seems like use cases for collections and products are covered, and leveraging an existing standard could provide the value of broad interoperability as well.

Thoughts/comments?  Apologies in advance if I missed this in the docs somewhere.

**Comment by cholmes** [comment]
Some consideration, though not a ton. I think a few people took a look at it and had trouble getting a real handle on it and how to use it. Your link above is a lot more interesting than what I've found on it - seems like a nice sensible description.

Lots of changes happening at the sprint, and it looks like the core is not going to be EO specific - is going to attempt to be general, to search sar, drones, video, satellites, etc. So core will be mostly space and time, and then extension mechanisms. But the EO 'extension' set would be great to align with OGC OpenSearch.

cc @matthewhanson

**Comment by uvoges** [comment]
Just to let you know: in the OGC EO-PMOS Standards Working Group we´re currently standardizing a new version of the OpenSearch EO-Extension (13-026r9 -> aligned with OWC Context, CEOS,...). Accompanied in a GeoJSON(-LD) response encoding (OGC 17-047), GeoJSON(-LD) based Metadata Profile for EO-products (granules) (OGC 17-003) and a  GeoJSON(-LD) based Metadata Profile for EO-collections (just in draft status). We hope to have final version by 1/2018.

**Comment by m-mohr** [comment]
@uvoges Where can we get more information about the current state of the new version of the OpenSearch EO-extension incl. the JSON response encoding? Sounds really interesting to me, but couldn't find much information on the web.

**Comment by uvoges** [comment]
All,

The draft standard will be available to the public as soon as the next review process (OGC Architecture Board) is complete. That will occur in the next two weeks. In the meantime, Uwe, you can send a draft to Matthias if your SWG agrees.

Best Regards,
Scott

**Comment by uvoges** [comment]
...ah, vom IfGI?
Schick Dir eine Version dann in 2/3 Wochen. Kannst mich ja noch mal erinnern...

VG, Uwe

Outlook for Android<https://aka.ms/ghei36> herunterladen




On Wed, May 9, 2018 at 10:20 PM +0200, "Matthias Mohr" <notifications@github.com<mailto:notifications@github.com>> wrote:


@uvoges<https://github.com/uvoges>
Uwe, thank you for checking on that. Having it in two weeks or so is soon enough for me. Where will the draft standard be published?
Grüße auf die andere Seite Münsters. ;)

**Comment by cholmes** [comment]
@m-mohr - did you manage to review this? Would be good to figure out if we can align some...

**Comment by m-mohr** [comment]
OGC released a draft open for comments on July 4, deadline was August 3. Unfortunately I missed the deadline as July was very busy and holiday season and the spec is hundreds of pages long or so. 

I had a brief look. I found it very hard to really get into it due to its massive length. Some comments follow...

Most interesting is probably the search functionality:
* Minimum set of search parameters they want back-ends to support: geo:uid, geo:box, time:start (not datetime, see #130), time:end
* Optionally, servers can support very advanced syntax, e.g. CQL.
* Collection search can search for productType, doi, platform, sensor, compositeType (a time period), processing level, orbit type, spectral range, wavelength, ...
* Additional INSPIRE obligated parameters for collection search: title, category, keyword, abstract, organizationName, publicationDate, lineage, contraints, language, ...
*  Product search has a ton (> 40) of parameters, I won't name them all, but they even include some really specific stuff like dopplerFrequency.
* I don't think OGC WFS considered OGC OpenSearch yet?! Seems to be different.

Regarding the JSON response format:
* They seem to put the links into the GeoJSON properties and also have objects in the properties, which we voted against (see our #143)
* Their link structure is actually an object, not an array (see our #197). The rel type is the object key.

Regarding the JSON metadata format:
* They support snow cover, would that be something interesting for our EO extension?
* Generally, we could get inspirations from the metadata format for our EO/SAR/... extensions.

Preliminary conclusion: Too complex for us and seems not easy to align (naming of search parameters, different JSON encoding regarding properties, ...).

PS: Not sure whether you can access the draft documents. We are an OGC member and seem to have access to more data than the public.

**Comment by uvoges** [comment]
Dear Matthias,

Before ging into detail, maybe next week, I would like to inform you that this candidate standard is currently already implemented by a lot oft space agency including:
- ESA
- DLR
- EUMETSAT
- CEOS
- CNES
- NASA
- ....
Nearly all EO Exploitation Platforms do support it. Some have implemented conformance/test environments, like NASA...

So simple does not always mean sufficient for all usw Cases...

Regards, Uwe


Outlook for Android<https://aka.ms/ghei36> herunterladen





Von: Matthias Mohr
Gesendet: Freitag, 24. August 16:11
Betreff: Re: [radiantearth/stac-spec] consideration of OpenSearch EO extensions (#16)
An: radiantearth/stac-spec
Cc: Uwe Voges, Mention


OGC released a draft open for comments on July 4, deadline was August 3. Unfortunately I missed the deadline as July was very busy and holiday season and the spec is hundreds of pages long or so.
I had a brief look. I found it very hard to really get into it due to its massive length. Some comments follow...
Most interesting is probably the search functionality:
Minimum set of search parameters they want back-ends to support: geo:uid, geo:box, time:start (not datetime, see #130<https://github.com/radiantearth/stac-spec/issues/130>), time:endOptionally, servers can support very advanced syntax, e.g. CQL.Collection search can search for productType, doi, platform, sensor, compositeType (a time period), processing level, orbit type, spectral range, wavelength, ...Additional INSPIRE obligated parameters for collection search: title, category, keyword, abstract, organizationName, publicationDate, lineage, contraints, language, ...Product search has a ton (> 40) of parameters, I won't name them all, but they even include some really specific stuff like dopplerFrequency.I don't think OGC WFS considered OGC OpenSearch yet?! Seems to be different.
Regarding the JSON response format:
They seem to put the links into the GeoJSON properties and also have objects in the properties, which we voted against (see our #143<https://github.com/radiantearth/stac-spec/issues/143>)Their link structure is actually an object, not an array (see our #197<https://github.com/radiantearth/stac-spec/issues/197>). The rel type is the object key.
Regarding the JSON metadata format:
They support snow cover, would that be something interesting for our EO extension?Generally, we could get inspirations from the metadata format for our EO/SAR/... extensions.
Preliminary conclusion: Too complex for us and seems not easy to align (naming of search parameters, different JSON encoding regarding properties, ...).
PS: Not sure whether you can access the draft documents. We are an OGC member and seem to have access to more data than the public.

**Comment by uvoges** [comment]
Dear Matthias,

I guess to develop something new from scratch which is easy to use and smart (being specific, considering a few use cases) is relatively simple and makes often sense. But when more and more organisations become involved the use cases to cover, the interopeability aspects, test cases.... and so the requirements increase.
That is a reason why the spec is lengthy. It covers lots of real life EO use cases and provides lots of specifications including detailed searches as required by: automated processings, Atom & JSON & JSON-LD clients, an ontology for EO products...
I guess search request and response are both interesting:
- the request covers e.g. very specific search cases as required  by automated hosted  processings
- the responses include 2-step search support (see spec), data-access (providing details incl OGC access services), the functionality is aligned with HATEOAS and Linked Data principles....
Loosely based on A. Einstein: "everything should be made as simple as possible, but not simpler."

The spec is already used by EO Integration platforms as e.g. CEOS/CWIC, ESA/FEDEO, Eumetsat/Wikeo etc and implemented by lots of Space Agencies (See my last email)..NASA and ESA have developed a test environments to test the implementations which will be integrated.

But it maybe also be good to have additional specialized and easy to use APIs for specific usw cases. We do the same in different projects: defining simple and easy to use Rest APIs based on Swagger/OpenAPI.
Please note: the latter will be discussed to replace the current OSDD/XML.

Some specific notes:

- CQL syntax is not in the main focus but can supported by specific implementations -> then it must be exposed within the OSDD...

- OpenSearch is an optional Conformance class of CSW 3.0 (as support of HTTP/Get/KVP is mandatory ->  support for OS can easily be added

Regarding the JSON encodings maybe Yves can provide  further details.

Hope this clarifies a bit the intention of OpenSearch-EO.

Best regards,
Uwe

Outlook for Android<https://aka.ms/ghei36> herunterladen



Von: Matthias Mohr
Gesendet: Freitag, 24. August 16:11
Betreff: Re: [radiantearth/stac-spec] consideration of OpenSearch EO extensions (#16)
An: radiantearth/stac-spec
Cc: Uwe Voges, Mention


OGC released a draft open for comments on July 4, deadline was August 3. Unfortunately I missed the deadline as July was very busy and holiday season and the spec is hundreds of pages long or so.
I had a brief look. I found it very hard to really get into it due to its massive length. Some comments follow...
Most interesting is probably the search functionality:
Minimum set of search parameters they want back-ends to support: geo:uid, geo:box, time:start (not datetime, see #130<https://github.com/radiantearth/stac-spec/issues/130>), time:endOptionally, servers can support very advanced syntax, e.g. CQL.Collection search can search for productType, doi, platform, sensor, compositeType (a time period), processing level, orbit type, spectral range, wavelength, ...Additional INSPIRE obligated parameters for collection search: title, category, keyword, abstract, organizationName, publicationDate, lineage, contraints, language, ...Product search has a ton (> 40) of parameters, I won't name them all, but they even include some really specific stuff like dopplerFrequency.I don't think OGC WFS considered OGC OpenSearch yet?! Seems to be different.
Regarding the JSON response format:
They seem to put the links into the GeoJSON properties and also have objects in the properties, which we voted against (see our #143<https://github.com/radiantearth/stac-spec/issues/143>)Their link structure is actually an object, not an array (see our #197<https://github.com/radiantearth/stac-spec/issues/197>). The rel type is the object key.
Regarding the JSON metadata format:
They support snow cover, would that be something interesting for our EO extension?Generally, we could get inspirations from the metadata format for our EO/SAR/... extensions.
Preliminary conclusion: Too complex for us and seems not easy to align (naming of search parameters, different JSON encoding regarding properties, ...).
PS: Not sure whether you can access the draft documents. We are an OGC member and seem to have access to more data than the public.

**Comment by sjskhalsa** [comment]
CEOS has published several versions of an [OpenSearch Best Practice Document](https://cdn.earthdata.nasa.gov/conduit/upload/6918/CEOS-OPENSEARCH-BP-V1.2.pdf) which may be a more accessible doc for implementing the OS EO Spec

**Comment by m-mohr** [comment]
I think we decided for now to not add OpenSearch to the STAC core due to its complexity, but it could be added as an additional query extension to the API. See #500 for ideas how to integrate more query languages.

One additional issue is that OpenSearch responses are not STAC compatible AND not GeoJSON compatible. OpenSearch defines a properties field in FeatureCollections, which is not allowed. This is something that should be fixed first.

**Comment by uvoges** [comment]
Dear Matthias,

1.
OpenSearch is a query capability which is (from an interface point of view) as simple as any other search capability which you support with the dynamic STAC catalogue. It is just a sequence of Name/value pairs provided in a HTTP/GET request...and GeoJSON or Atom response...

2.
With the OGC OpenSearch EO Extension we are not aligned with STAC as STAC does currently Not cover the more complex use cases which were defined by ESA, NASA, Eumetsat, Vito, DLR, etc in the Context of CEOS/CWIC, FedEO etc. We got much more requirements for the query capabilities and for the responses than STAC currently supports -> See OGC 13-026r9, 17-047, 17-003

3.
To align with the OGC stack, here OWS Context, we needed to accept the GeoJSON Bug which is a Bug in OWS Context, Not in OpenSearch-EO.

Thanks and best regards,
Uwe

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
