### ISSUE TITLE
Relative vs. absolute links

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#160]
Should links within a catalog hierarchy be absolute (all links fully qualified) or relative (to `self`, which can substituted with the URL that the document was fetched from)?

Pros / cons: portability, difficulty of resolving individual links, etc.

**Comment by jeffnaus** [comment]
Discussion with sprint-3-static group:

Absolute links are required in order to link to external resources.
Absolute links are required for self (is self still required).

Relative links can break when end users pull the records local
The problem of updating links when moving can be overcome.

There are cases in machine learning and other processing where the desire it to copy the whole "directory" and in this case relative links are very useful.

**Comment by m-mohr** [comment]
I think this has been fixed and can be closed.

**Comment by 60south** [comment]
I realize this issue is closed, but it's what popped up when I went in search for a solution...

@jeffnaus wrote:
> The problem of updating links when moving can be overcome.

What do you suggest?

In brief: We are looking at implementing STAC for a large volume of near-real-time remote sensing assets. As the asset files age they will be archived from expensive (fast) storage to longer-term, cheaper storage locations. Of course, this will break any absolute links. As I see it, we have a couple options:

- Update the links in each STAC item. This means browsing through the items will be broken until the STAC Items have been re-crawled/re-indexed, which will need to occur continuously. Since the assets may be moved _several_ times, this could get very messy.

- Replaced moved assets (and STAC Items) with permalinks that refer to the new locations. We'd still need to maintain these, but it's fairly easy and instantaneous. (This is what we're thinking of doing.)

Is there another approach we should look at?

**Comment by m-mohr** [comment]
The suggested solution for your use case was that you use relative links for all links except the link with the relation type `self`. This still allows navigation through the catalog and updating can be done later as only the reference to `self` needs to be updated. See also https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#relation-types
