### ISSUE TITLE
Rename eo extension to satellite eo

### ISSUE THREAD

**Issue by omad** [radiantearth/stac-spec#171]
Several people have pointed out that the current `eo` extension is very specific to satellite earth observation data, including many fields which are specific to satellite data, but not eo in general.

To avoid confusion we should rename the extension and prefix to better indicate their purpose.

**Comment by fredliporace** [comment]
EO as defined at the moment fits very well to 'Satellite-Optical-EO' domain, with some fields that also apply to other domains such as SAR (see #155) but others that do not. The nice thing about being more specific about the extension domain is that the domain works as a guide to people implementing the SPEC, defining the attributes that are considered to be relevant by the users.

I would go to with extensions for each domain such as Satellite-Optical, Satellite-SAR, etc., and later when this is more consolidated try to work on structuring the common attributes between domains.

**Comment by matthewhanson** [comment]
Not really fond of satellite-optical. Optical remote sensing refers to the part of the spectrum of visible through short-wave IR. However, mid-wave and long-wave IR bands (which are not considered optical because of the thermal sensing component) are often included and packaged together (ie Landsat) and can easily be included in this extension, especially MWIR which has the same units of reflectance as the optical bands.

So having optical is a bit of a misnomer if data using this extension includes MWIR and LWIR which is certainly possible. What is wrong with satellite-eo?

**Comment by simonff** [comment]
"satellite-eo" would imply it covers radar data, but it does not. Conversely, it can apply to aerial imagery, but the name precludes it. Maybe "passive" for optical/IR/MWIR/microwave and "active" for radar?

**Comment by cholmes** [comment]
+1 on the change - happy for whatever name you all agree on.

And yes, it's cool if other extensions like SAR and Drones share some of the fields here - indeed it's encouraged. Once we get those fleshed out we can elevate some to a common extension that they can share.

**Comment by matthewhanson** [comment]
@simonff Yes, that is true, I suppose that having a name that suggests SAR when it does not is worse than a name that suggests it only includes Visible-SWIR when it does not.

So something including "optical" would be the most descriptive, but we should include in the description that many "optical" sensors often include midwave and even longwave IR bands even though they technically aren't optical.

Maybe eventually we might see a separate but similar extension for thermal remote sensing. But for now I think that the occasional sensor that publishes thermal bands alongside optical bands is fine.

so, with that in mind I propose we change the name to EO extension, standing for for Electro-optical, which refers to the Vis-SWIR range, rather than Earth Observation. :-)

It could be sat-eo, but as pointed out this extension as is can be used for drone imagery.

**Comment by fredliporace** [comment]
@matthewhanson you've got me thinking on that but my view is that, at least from the payload side, TIRS for example is an optical sensor - it has an optical subsystem. I agree however that from the applications side the term optical and its connection to visible may be confusing. I'm ok with Electro-optical.

**Comment by simonff** [comment]
I support EarthOptical for its pun value.

Reiterating Matt Hancher's concern that I mentioned in giitter: "Maybe it's better to have fewer larger extensions (even if some of their fields go unused in some cases) rather than a lot of hyper-specialized extensions."

**Comment by cholmes** [comment]
+1 for EarthOptical. But again, I'm cool with whatever, and Electro-optical sounds good too. And keeping eo prefix sounds good.

I think we should aim to get to some sort of 'master extension' for all the different types of sensors, so aspire to what Hancher proposes. But I think we should start narrower with things we know, and let the parts (drone, sar, mosaics, etc) develop a bit independently, and then group them. But perhaps we could put them all in the same folder under extensions? So group them by a folder, but stop short of saying 'this is one larger extension'...

PR welcome if someone is up for doing the rename.

**Comment by m-mohr** [comment]
Every extension should live in its own folder anyway and not on the top level of extensions like EO and collection. You usually already should have three files at least (schema, spec, example).

Once there is another +1 I'll prepare a PR.

**Comment by matthewhanson** [comment]
+1 for Electro-Optical (did I already vote?)

**Comment by m-mohr** [comment]
EarthOptical: @simonff and @cholmes 
Electro-Optical: @matthewhanson, @fredliporace and @cholmes 
It was a draw before, that's why I asked for another +1.
So seems like Electro-Optical is the winner.

**Comment by simonff** [comment]
I actually meant to support ElectroOptical as well, just to get things going, though this Freudian slip  indicates that this name is fragile as well.

**Comment by matthewhanson** [comment]
resolved with PR #276
