### ISSUE TITLE
naip-sample.json is invalid

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#204]
The naip-sample.json has a property ``naip:keywords`:
```
        "naip:keywords": {
            "place": {
                "place_keyword": "STAPLETON",
                "place_keyword_thesaurus": "Geographic Names Information System"
            }
        }
```
That is an object and therefore should be outside of the `properties` object. All properties are expected to be "flat" (i.e. no arrays and objects).

**Comment by cholmes** [comment]
I think we can fully kill the naip examples... They weren't super well thought out. Would be nice to eventually have a NAIP example, or indeed a full NAIP catalog as STAC. Hopefully @scisco will do that in scope of his work of converting more of AWS imagery catalogs to STAC. And then we'll have real world examples instead of guesses of what an example could look like.

**Comment by m-mohr** [comment]
Killed them.
