### ISSUE TITLE
UML diagram for STAC 0.6.0

### ISSUE THREAD

**Issue by hgs-msmith** [radiantearth/stac-spec#286]
Here is an updated diagram that captures the model pending final 0.6.0 merge (#260).
[STAC-060-model.pdf](https://github.com/radiantearth/stac-spec/files/2474553/STAC-060-model.pdf)

**Comment by matthewhanson** [comment]
@hgs-msmith it would be good to get this image added to the repo somewhere for the final 0.6.0 release

**Comment by cholmes** [comment]
Moving to 0.6.0  Agree it'd be nice to have an image in somewhere. Not sure exactly where it should go...

**Comment by fredliporace** [comment]
This kind of diagram is *very* useful in understanding and discussing the model. It was my main reference while updating from 0.5 to 0.6.
Some comments:
 - I think that the relationship between collection and catalog should be inheritance
 - Maybe this is a style thing, but I prefer that the attribute name should not be explicit in the class when the composition relationship is used. For instance,  I would remove 'geometry' from the attribute list of 'item' since that attribute name is already defined by the 'item'/'geometry' composition relationship.

**Comment by m-mohr** [comment]
I agree, the diagram is useful. Thanks @hgs-msmith , but I think we need to improve some more things before releasing it officially.

@fredliporace Yes, the relationship between collection and catalog should be inheritance.

Other than that, I'd simplify the diagram a bit and remove the descriptive text boxes for links ("links apply to...") and rel types ("rel types common to..."). The link box itself should connected to catalog, item and collection. I'd also remove the (`(producer | processor | host)]`) from the provider type.

We have cardinalities for eo:bands / eo, but not for the other relations. We should either add them or remove them.

I think bold text could be used to mark required fields. It's not really clear why links, eo, properties and link are bold.

Asset has two elements `type`. One should be `title`.

**Comment by fredliporace** [comment]
@hgs-msmith 

I prefer PDF over the embedded image.

I'd say yes, a collection is a catalog from what I read in the spec text description. The example of structure of nodes being a mix of catalogs and collections is exactly what @m-mohr suggested in the gitter channel. One exercise that may be done is to replace in the spec "Catalog or Collection" by simply "Catalog". If that can be made without any trauma then it reinforces that indeed a collection is a catalog.

I agree about the relationship between collection and catalogs, but maybe it should be better to represent the links as associations and not as aggregation/compositions. What do you think? We could then use the association name to specify the rel (root/parent/etc).

I see no problems in the descriptive texts, AFAIK a comment/note is valid UML and should be used whenever the diagram itself leave ambiguities or do not cover important information, such as which 'rel's are valid for a given class. Note that for the example @m-mohr gave maybe using associations to represent the links would possibly remove the need for the comment. I'm not sure however if it is possible to include all the relevant link object information as association attributes.

**Comment by fredliporace** [comment]
![stac-association](https://user-images.githubusercontent.com/28077347/47183728-2ab81280-d2ff-11e8-9e63-6b76aa7d92ab.jpg)

This is an example of the concept I presented earlier. Note that the Item->Collection relationship could be represented by 'parent' in Item, its just a special case when the parent is a Collection.

**Comment by hgs-msmith** [comment]
Attached is an updated version of the diagram in which I have tried to address the issues raised in this discussion. The biggest change is that I've attempted to capture the semantic meaning and cardinalities of the link relations between catalogs, collections, and items, following the suggestion of @fredliporace. Let me know it this adds clarify or ends up being just too much information. And, of course please check the content for accuracy. Thanks!

[STAC-060-model.pdf](https://github.com/radiantearth/stac-spec/files/2497066/STAC-060-model.pdf)

**Comment by fredliporace** [comment]
@hgs-msmith thanks for the update! I like the way you represented the cardinalities. Some suggestions/comments:
 * I would remove stac_version, id, description & title from collection since they are already represented in the catalog. It would be easier that way to visualize the properties that are specific to collections.
 * It seems that Items are not required to link to collections, parent and root.
 * The 'derived_from' between items is not represented.

**Comment by matthewhanson** [comment]
@fredliporace A Collection has to have the required fields of a Catalog, because it is a Catalog. An id description and title all apply to the Collection, they may be different for the parent Catalog.

stac_version is needed in every Catalog and Collection, because a user could enter the tree at any node, and needs to know the version. Also, a Collection could technically be the root catalog.

**Comment by fredliporace** [comment]
@matthewhanson what I meant is that if every collection is a catalog there is no need to represent the catalog properties again in collections. Their place in collection is a consequence of the inheritance relationship.

**Comment by m-mohr** [comment]
Theoretically, I support your @fredliporace . But practically, only people with UML knowledge will understand that. Maybe the current state is easier to understand by an "average" user?

**Comment by matthewhanson** [comment]
resolved with https://github.com/radiantearth/stac-spec/pull/324
