### ISSUE TITLE
Adopt camelCase for property names

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#305]
We've been using snake_case since the beginning. However, WFS 3 uses camelCase for property names, so we should consider aligning for stylistic purposes.

The only properties in the core spec (introduced for 0.6.0, so this could go into the next RC) that would be affected by this are:

* `stac_version` → `stacVersion` (`Catalog`, `Collection`)
* `derived_from` → `derivedFrom` (relation (`rel`) types)

This has implications for extensions, but since they're extensions, they can basically do whatever they want.

**Comment by cholmes** [comment]
Funny, I hadn't even really realized that WFS 3 did camel case, since the properties in the main responses are all one word. 

I think I was the one who did snake case, as stylistically I just have never liked camelCase... Though I do really like aligning with WFS, so I'm conflicted. 

Is there any more context for this? Like why people make these choices in the first place? Looks like there's some discussion at https://www.quora.com/Which-is-better-snake-case-or-camel-case-pascal-case#

**Comment by m-mohr** [comment]
> Is there any more context for this? Like why people make these choices in the first place?

I think this is really specific to the domain/programming language and probably in most cases is just the choice of the original "author" based on their subjective preference. It is the same here: Chris decided for snake_case for STAC, a colleague of mine decided for snake_case for openEO, etc. If you ask WFS3 for snake_case vs. camelCase they'll probably answer similar things.

**Comment by mojodna** [comment]
I don't have an independently strong opinion between the 2. When I do, it's according to local norms of the language I'm using--Python, definitely snakes, JavaScript, camels for life, C#, Pascal is my god--and it's just weird/jarring/an indicator of the author's native language when things don't match.

In this case, WFS3 owns the local norms, so we should follow its lead to keep things internally consistent.

**Comment by m-mohr** [comment]
Closed as discussed in #318.
