### ISSUE TITLE
Disambiguating Collections from Catalogs

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#306]
We should document rules (or provide explicit clues) for disambiguating `Collection`s from `Catalog`s. Alternately, consider that the distinction doesn't matter.

For example, is this a valid `Catalog` with additional properties or a non-validating `Collection` (due to the lack of `extent`)?

```json
{
  "stac_version": "0.6.0",
  "id": "planet-disaster-data",
  "version": "1.0.0",

  "description": "[Planet Disaster Data](https://www.planet.com/disasterdata/) makes imagery available directly to the public, volunteers, humanitarian organizations, and other coordinating bodies in support of the International Charter for Space and Major Disasters. Data is released for individual disaster events, providing a 30 day window pre- and post-disaster. Imagery is provided under Creative Commons licenses, free of charge, with either CC-BY-SA or CC-BY-NC.",

  "license": "CC-BY-SA-4.0",

  "links": [
    {
      "rel": "self",
      "href": "https://storage.googleapis.com/pdd-stac/disasters/catalog.json"
    },
    { "rel": "root", "href": "catalog.json" },
    {
      "rel": "child",
      "href": "hurricane-harvey/catalog.json",
      "title": "Hurricane Harvey"
    }
  ]
}

```

**Comment by mojodna** [comment]
I'm approaching this from the consumption angle; if I encounter one of these in the wild (or when validating), how should I treat it? Does the answer vary depending on whether it was traversed to from a link with `rel=parent` or `rel=collection`?

If I deem it to be a `Catalog`, should `license` apply to children, or does that only apply if it's a validating `Collection`?

**Comment by m-mohr** [comment]
I think, you should read additional information only from rel=collection. At least that is the way we designed it and why there is this additional relation type. rel=parent and rel=root can be collections, too, but the most relevant collection for an item should be linked with rel=collection from the provider so he advises us to take information from there. If a field is missing, it is invalid but we usually should be able to read the other information anyway. I personally wouldn't really handle the other information from parent or root and make assumptions. Is my idea clear? I think it should answer all your questions.

**Comment by mojodna** [comment]
So:

1. read the root (catalog)
2. ignore collection properties (apply catalog validation rules)
3. traverse to find items
4. traverse `rel=collection` to (re-)load associated collection (apply collection validation rules)
5. apply collection properties to item

Is this what you were thinking?

**Comment by matthewhanson** [comment]
I've been thinking about these same issues while developing sat-stac. From the standpoint of being able to traverse catalogs, find collections, find items, update collections or items, or create whole new catalogs and add collections and items to them, it's definitely useful to be able to determine the difference between a Catalog and a Collection.

Right now in sat-stac, in order to be able to find any child collections underneath an arbitrary catalog I have resorted to checking if the catalog has an 'extent' field. If it does, it instantiates it as a Collection (so that we can then use it as a Collection and do stuff like add Items to it), otherwise it instantiates it as a Catalog.

I think the links work fine, and I'm good with Catalogs using rel='child' links to point to other Catalogs OR Collections. However, once I follow that link it would be better to be able to unambiguously differentiate between a Catalog and Collection.

I posted this in gitter, but here's a notebook showing some of these concepts as:
https://gist.github.com/matthewhanson/151015ad32c84f92100f697b5ec5496d

**Comment by mojodna** [comment]
> I guess I'm wondering Seth if you think the above is too annoying for a client to implement? Or if it is reasonable?

It seems reasonable. Agreed on the "display extra properties if present" point as well.

**Comment by m-mohr** [comment]
The process depends heavily on the use case, so the 5 steps @mojodna lists above could be suitable for ingestion, but may be not so good for humans browsing a catalog in STAC browser. The browser would more likely just "display extra properties if present". Chris wraps this up quite good.

Programatically, a strict check for collections would be something like:
`if (c.isCatalog() && c.hasExtent() && c.hasLicense() && c.hasProviders()): # It's a collection`

**Comment by m-mohr** [comment]
Should we add a note to the next release regarding this?

**Comment by matthewhanson** [comment]
I'm not sure if there's any action to take on this now?

Seems like we're good with the way things are. Also note that according to best practices, for static catalogs, a catalog will be called 'catalog.json' and a collection 'collection.json'.  It doesn't help with disambiguating when traversing.

Do we need to add in any further clarifying language?

**Comment by mojodna** [comment]
At this point, probably not. Having it in the issue tracker means other people can find this and re-raise it if they have similar problems.
