### ISSUE TITLE
Item-level license and providers

### ISSUE THREAD

**Issue by mojodna** [radiantearth/stac-spec#307]
For `Item`s that are difficult to group into coherent `Collection`s, we should provide a clearly-defined mechanism for specifying their `license` and `provider`s.

In other words, `license` and `providers` are important enough properties that they should be calculable for a given item, either directly or via the `Collection` that it belongs to. `Item`s that only belong to `Catalog`s are currently orphaned with no license data.

OpenAerialMap is a collection of heterogeneously-licensed data (differing CC licenses) provided by a variety of users. In order to surface licensing data for individual items, a `Catalog` would need to consist of multiple `Collection`s per user, one for each license used by that user. To further complicate things, legacy imagery does not include user associations. Complicating things even *more*, user uploads may have varying [free-form] attribution.

From Gitter:

@cholmes:

>  for OAM I'd have many collections. It can be one 'catalog' at the highest level, and then you'd navigate down to like the user level, and perhaps each user (or user + specific drone?) would be a 'collection'.

@matthewhanson:

> The license thing had come up before, when Jeff at DG mentioned license might vary in a collection.
> I think for OAM there's lots of other good reasons to make different collections for the data (varying platforms, instruments, spectral band definitions, etc), however for some collections it is useful to group together things from multiple sources. I'm currently working on making a collection that represents a specific area, with mixed imagery as member Items, so the license thing is pertinent there as well (it could be DG imagery, or publicly available imagery).
> We could solve this pretty easily by moving license into the Item properties. It could then be specified using the Commons extension in the Collection, or not and just specified per Item.

@m-mohr:

> You are taking a subset of a collection and merge it to another collection, so to me it would be clear that there should be multiple collections involved.
> If we are stripping away license from collections for that reason, we would also need to strip provider. Your combined imagery probably doesn't only have different licenses, but also different providers. And basically, the same applies for the extents. So we are basically back to discussing usefulness of collections as we would strip away all fields that separate collections from catalogs. Really? We just discussed that in depth...

**Comment by mojodna** [comment]
Allowing `license` and `providers` into `Item` `properties` has the additional benefit of making `Item`s more self-contained (no need to look up `rel=parent` or `rel=collection` (if present) or `rel=root` for additional metadata).

**Comment by m-mohr** [comment]
What's the question here? (you added the question label)

What would happen in case of conflicts? Different license in collections and Items for example? Do we really need to cover this use case? Why should Items be self contained? It replicates data a lot. Varying [free-form] attribution is not really something one would search for, so not sure whether it it is too useful. Just some thoughts.

**Comment by mojodna** [comment]
Can/should we specify that `license` and `providers` are optional `Item` properties?

**Comment by mojodna** [comment]
I was using free-form attribution as a reason why modeling OAM as a collection of per-provider `Collection`s would be difficult. I would rather add a `child` to a single `Catalog` than have to look up (and create, if necessary) the specific `Collection` that matches a specific set of criteria when new imagery is uploaded.

In the case of a conflict, I would defer to the "local" definition (i.e. if `license` is provided for both and `Item` and a `Catalog` / `Collection`, the `Item`'s would be preferred).

Self-contained items are a side-effect of this; the fundamental reason I think it's important is to allow simpler modeling of heterogeneous datasets.

**Comment by m-mohr** [comment]
I had a look at OpenAerialMap and to me it seems as those Items ([example](https://map.openaerialmap.org/#/-18.45703125,18.47960905583197,3/latest/5bc5bdec4d3b1b00050eeead?_k=dqloyz)) you are talking about should be individual collections. They all have different providers, titles, licenses, and differ in so many different aspects that I'd naturally think about them as individual collections. To me OAM is just a catalog of collections, similar to the GEE dataset catalog.

So, I'd say no, provider and license are clearly things that are more on the collection level as on the item level. Maybe there are better (just my opinion) examples as OAM for this issue?

**Comment by mojodna** [comment]
> To me OAM is just a catalog of collections, similar to the GEE dataset catalog.

This makes sense to me (and lines up with the old "scene" / "image" relationship). Does it mean that each item will need both an `Item` and a `Collection` created for it?

If so, it's appealing to be able to fold `Collection` properties into the `Item`, i.e. `license` and `providers`, and eliminate the `Collection`.

**Comment by cholmes** [comment]
I'm thinking we should consider putting license and provider back in to `Item` for 0.6.0, since it is something we are actively taking _away_. I had thought that the collection would cover every use case, but having OAM provide a counter example gives me some pause. 

I do think there may be an answer in making it so you can define a 'Collection+Item' in one file, but it seems less good to make users define a whole collection link to share a single item with provider and license.

I think we can recommend the collection route, but leave provider/license as an option for those cases that aren't defining a collection, and that one of the two options needs to be defined.

Open to discussing and figuring out a way forward in the next week or two, but I think here the conservative thing to do is to leave license and provider in as optional fields in the Item for now, until we have a really solid answer. I suppose the other issue is we changed provider to providers and made it an array. So this also touches on the 'general metadata model' that we also want to figure out. 

Like the answer could be that 'commons extension' becomes core and license and providers are specified in the 'properties' of a collection, and an item can choose to refer to its collection or have it inline.

**Comment by matthewhanson** [comment]
Having license and providers as Item properties allows them to be used in the Commons extension and defined in the Collection. This only adds flexibility for data providers on how they organize their data, so I'm open to that.

As far as over-riding a Collection level, that's something we really want to avoid. Right now, Item's are not allowed to specify any property that is contained in it's Collection properties. Opening the door to do so means that the Collection ceases to be an accurate depiction of what the catalog is, and instead only represents default values. As a user I want to be able to look at a Collection and see what it is that ties together all these Items. If license and providers are not in the Collection that tells me that this is a collection of Items across providers and with varying licenses.

**Comment by m-mohr** [comment]
We can stil model OAM with STAC, you just need to use the collections. Are there more counter examples? For collections with a single image as in OAM it is certainly not a single file anylonger per "element", but I think we gain a better structure and clear architecture. There are more reasons why I think collection-level data shouldn't be partially mixed with Items:

1. It is duplicating information. Having the same fields specified in two places makes the spec unintuitive and confusing. You have two place where providers could specify there data and consumers need to look in two places for the information. With the commons extension data could also conflict. Conflicts need to get resolved, but as far as I understood recent discussions, we don't really want to do that. It would lead to discuss inheritance in the spec.
2. Just because something wasn't well thought out before doesn't make a good argument to leave it in the spec. At some point things need to deprecate ideas when there is a replacement.

> Does it mean that each item will need both an Item and a Collection created for it?

@mojodna In case every collection in OAM only contains a single image, yes. But there are these images provided by "Astro Digital" that are basically covering the whole global, I think. In theory, these would be a good collection if grouped together.

> If so, it's appealing to be able to fold Collection properties into the Item, i.e. license and providers, and eliminate the Collection.

@mojodna I would say it should be the other way. As we can already have the commons extension, you could simply use that to fold it into a collection! As there is only a single image, everything is common and could be added to the collection. Unfortunately, the GeoJSON properties are not part of the common metadata model and can't be shared. (Why not?) If we implement #310 it seems odd that id and title are on different levels and title could be shared, but id can't.

> Like the answer could be that 'commons extension' becomes core and license and providers are specified in the 'properties' of a collection, and an item can choose to refer to its collection or have it inline.

@cholmes That opens the question: What do we need collections for in this case? Keywords, version and extent are left. Version could also be useful per Item, keyword as well (see OAM) and extent also. Though we would have a problem here with the bbox not being in the common metadata model (instead it is in GeoJSON, see also #310 ). So let's drop collections again? (just kidding!!)

Seems like item-centric and collection-centric viewpoints are clashing again.

**Comment by mojodna** [comment]
>  In case every collection in OAM only contains a single image, yes. But there are these images provided by "Astro Digital" that are basically covering the whole global, I think. In theory, these would be a good collection if grouped together.

Astro Digital's OAM contributions are definitely the exception rather than the rule (and will disappear soon, as their bucket is no longer accessible).

OAM is definitely an outlier here, as it's an example of a repository of user-contributed content vs. single-source data providers elsewhere.

@m-mohr I'm open to merging `Item`s into `Collection`s, but as you note, the common metadata model makes that more difficult than merging `Collection`s with `Item`s.

> Just because something wasn't well thought out before doesn't make a good argument to leave it in the spec. At some point things need to deprecate ideas when there is a replacement.

Yes, definitely. I don't see a good replacement yet, though.

Maybe what I'm actually asking here is: "is the use of `Collection`s optional?"

**Comment by m-mohr** [comment]
> OAM is definitely an outlier here, as it's an example of a repository of user-contributed content vs. single-source data providers elsewhere.

There are probably more outliers that we would need to cover, but we need to find them and see whether we can model them with the current STAC proposal.

> @m-mohr I'm open to merging `Item`s into `Collection`s, but as you note, the common metadata model makes that more difficult than merging `Collection`s with `Item`s.

The difficulty is not really the common metadata model. The problem to me is GeoJSON and their properties. If we wouldn't use the properties but put everything top-level, it would be easier to just say that the GeoJSON fields are also included as part of the common metadata model! 

> I don't see a good replacement yet, though.

Collections are the replacement, in my opinion. Why is that not good?

> Maybe what I'm actually asking here is: "can I opt into using `Collection`s?"

Yes, please use collections for it! :-)

**Comment by m-mohr** [comment]
I'm just wondering whether we could do something like a "Single-Item-Extension"? So that we don't confuse providers with provider and license in the core item AND collections specs, but make an extension that simply says: If you want to provide single items as collections, please use the "single-item" extension, which has some/all the fields the collection spec has?!

**Comment by cholmes** [comment]
Discussed on the call 8/23. In general the consensus was that this should be handled by a 'common metadata model', and that a 'single item extension' or something like it would be good - enable people to define all the collection fields in their item. This is a bigger discussion and will be in 0.7.0. 

For 0.6.0 the decision is to make an extension that defines the provider and license properties for use in an Item. These will use the collection definition. There was an idea to just put them in core, but hesitation because we redefined 'provider', and it's no longer flat (and there is still a desire to just have flat things in the core).
