### ISSUE TITLE
Add querying capability to STAC api

### ISSUE THREAD

**Issue by cholmes** [radiantearth/stac-spec#31]
The key feature of the API is to enable querying, but the group did not define a full query mechanism at the boulder sprint. Implementing groups should feel free to propose a mechanism to query metadata fields

**Comment by joshfix** [comment]
I'm pretty sure @kasey was looking into filter expression implementations and I don't know that anybody came up with anything good.  I asked Clemons Portele what they had in store for WFS 3 and this was his response:

> We have not looked into the question how we will express richer queries in WFS 3 than what we currently have in the core part. 

> Personally, I would like to reuse something existing that is used elsewhere and where supporting libraries exist (at least for the non-spatial part), but we have not discussed this yet. I would expect that in November and maybe December we will focus on the core part and move to additional capabilities later in December or January.

I think this is a pretty complex issue and our best bet may be to wait and follow OGC's lead on this.  There may be better solutions in the future that can be released in later versions, but coming up with a solution/standard on our own right now may be a bridge too far.

**Comment by osialr** [comment]
Core-api discussed query but felt that requiring anything more than geo and time could be a burden for very simple catalogs. 

PIXIA's catalog supports ECQL as a query language.  We've found it expressive enough so far.  It has a BNF definition that allows us to use a computer generated parser and add our own hooks on translation.  

http://docs.geoserver.org/stable/en/user/filter/ecql_reference.html

I could see that as an codified extension.  One downside is that geometries are specified as WKT, and so clients have to convert from geojson to wkt.

**Comment by osialr** [comment]
You could also start with CQL since it is already hosted on the OGC website.   It's missing a few luxuries such as `field IN (1,2,3)` and `ILIKE`, but could get the ball rolling.  

For example, CQL is described in Appendix B of _OGC Catalogue Services 3.0 - General Model_ (document `12-168r6`)
http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#62

**Comment by cholmes** [comment]
Yeah, I think it could be a good little 'extension' to start with. I do think it'd be good to publish it as its own mini-spec (or get OGC too) - I've always found it so weird that it's buried in catalog services. Like the filter encoding group should take it on. 

Ideally I think we'd also slim it down a bit to just a subset, like cut out the more complex geometry operations like 'crosses' for simple implementations.

**Comment by arthurgustin** [comment]
Hello, I discovered the STAC project yesterday and I'm very interested. I can't talk in the name of my company but maybe we will end up doing something.
We already have a research API, and it's a mix of opensearch, ECQL, with company-specific metadata and common metadata.

Geometries are requested in WKT format, like the following example:

    `/search?q=foo&g=POINT (42 42)&relation=intersect` 

With g = any WKT geometries and `relation=disjoint|intersects|contains|within`

Other operators with brackets:

`/search?q=foo&snowCover=]56.6&acquisitionDate=[2017/08/29,2017/09/30]`

-> snowCover strictly > 56.6 AND acquisitionDate between 2017/08/29 2017/09/30 both included

However, this API is limited because we don't have the NOT and the OR operator, but still it covers most of the use cases.
For more complex queries we implemented a csw catalog with has infinite possibilities

I hope I can be of any uses in this project :)

**Comment by cholmes** [comment]
@gsf-trutherford - I think you said you're up to take this on? Making a proposal on a query language based on mongo/elastic, in line with what @kasey did? I just added you as a collaborator on the repo. Let me know when you accept, and I'll assign the issue to you.

**Comment by gsf-trutherford** [comment]
@cholmes I intended to get something together earlier this week, but I had a few things come up in the day job. It is definitely on my list still!

I don't have a complete grasp on what @kasey did, but I liked the "gt" "lt" approach and I think I will borrow from that. I think the proposal will be somewhere in the middle of what I saw from the active catalog presentations. So hopefully it will strike the right balance. I will definitely be interested in reaching a consensus rather than pushing an agenda.

**Comment by cholmes** [comment]
Awesome. Main thing I meant by 'in line' was just trying to get something that is simpler on the backend than CQL / full SQL WHERE type clauses. So I'd guess anything inspired by mongo/elastic likely works, and I'm sure Kasey will sound in with feedback.

**Comment by cholmes** [comment]
I think we're good with this! Thanks @hgs-trutherford for pushing this forward. More filter extensions will be good to see but I think the core is there.
