### ISSUE TITLE
Add instrument mode field in the EO extension

### ISSUE THREAD

**Issue by p3dr0** [radiantearth/stac-spec#353]
This field is defined as: 

- mode (or sensor_mode) : string : A string identifying the sensor mode (e.g. stripmap)

The sensor mode as a wide range of uses. It can describe support modes or operation modes (e.g. Auxiliary, Calibration and Measurement). For radar satellites, it is also quite important when describing different acquisition modes (e.g. Stripmap, Interferometric Wide Swath, Extra Wide Swath, Wave).

![image](https://user-images.githubusercontent.com/1179031/48497846-367ef200-e835-11e8-8325-44ebe4ab72f5.png)

Source
https://sentinel.esa.int/web/sentinel/technical-guides/sentinel-1-sar/sar-instrument/acquisition-modes

**Comment by m-mohr** [comment]
Sentinel-1 will be described with the SAR extension (#347). The EO extension is better suited for MSI, OLCI etc., but is not well-suited for SAR data.

For SAR, we have instrument_mode in the proposal. That's probably a free-form string, but can we standardize that to some extent? Otherwise useful searching on this field will be hard to realize. For example "Stripmap" and "SM" seems to be the same and therefore should be either Stripmap" or "SM", but not both. Same applies for IW, EW etc. 

For EO, what kind of data would be added to the instrument_mode field?

**Comment by matthewhanson** [comment]
I wouldn't want to add a field for mode if it was a free-form string. We need to have an enumerated list for it.  I could see 'operational' and 'calibration' as mildly useful...even though most catalogs probably aren't going to contain calibration data.

**Comment by m-mohr** [comment]
instrument_mode was added to the SAR extension some weeks ago, I think this issue is therefore solved?
