### ISSUE TITLE
Satellite extension / similar fields in extensions

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#356]
Now that we are soon getting more similar extensions (e.g. EO, SAR) that share a certain number of fields (platform, constellation, instrument, orbit, ...) we should think about extracting them into a separate extension or so. Could be Satellite (`sat`) for example, but platform / Instrument could also apply for drones or generally non-satellites, so we need to carefully decide this in the future.

Not necessarily required for 0.7, but sometime in the future. Opening this now so we don't forget it.

**Comment by cholmes** [comment]
Relevent discussion in #357

**Comment by m-mohr** [comment]
Another issue that we are facing is that people are confused by the EO extension. They assume EO means earth observation and are not sure whether SAR has to be used in addition or is a separate thing. Having EO as Electro-Optical does not seem intuitive. The question is whether we want to combine common fields in EO and SAR into an EO extension and move purely Electro-Optical fields into someting like an Opical extension. @mojodna

**Comment by geospatial-jeff** [comment]
>  people are confused by the EO extension

I'm one of these people.  I think it is trying to do too much.  It has information about the projection (epsg) and sensor (sensor/instrument/gsd, bands) and scene-level metadata (off_nadir/sun_azimuth/etc.).  Rather than a one size fits all solution, I like the idea of strategically crafting extensions around the raster data model.

This is why I really like the proj extension; it does a good job of describing the coordinate system of the image, an important part of the raster data model.  It provides a single, standardized, and independent way of searching the projection of raster data.  It's more intuitive to use than remembering that epsg is hiding in the EO extension and will maintain separation of concerns because the extension does what it is designed to do and nothing else.

I like the idea of a `sat` extension (`aerial` and `drone` extensions as well) for the same reason.  The extended raster data model acknowledges that raster data doesn't exist on its own but comes from various sensors (SAR/electro-optical/LIDAR etc.) attached to a certain platform (usually drone, aerial, or satellite) which are sensing the target (in this case the Earth) under various conditions (cloud cover etc.).

A `sat` extension nicely abstracts an important component of the raster data model and allows some properties to be offloaded from the EO extension.  Personally I think that gsd, platform, constellation, instrument, and bands would all be more appropriate in the `sat` extension.  I would argue these fields are intrinsic properties of the specific platform/sensor whereas extensions such as SAR/EO which are describing sensor-specific, item-level metadata should be exclusively concerned with extrinsic properties such as cloud cover, nadir angle, etc.

**Comment by m-mohr** [comment]
> Personally I think that [...] bands would all be more appropriate in the `sat` extension.

While I agree with many of your point, I don't agree with the bands. They are too different between EO and SAR. You could argue to define a basic set of band properties and extend it in EO and SAR, but I would think that it would be too complicated to maintain and validate. Also, I'm not sure whether we should introduce extension inheritance. 

> A `sat` extension nicely abstracts an important component of the raster data model 

If it abstracts raster things, why not call it `raster`? I don't think many of the `sat` fields you mention would be exclusive for satellites, but would also apply for aerial or drone. So I don't quite get your argumentation here because it mixed sat and raster.

**Comment by geospatial-jeff** [comment]
>  I don't agree with the bands. They are too different between EO and SAR.

My reason for moving bands out of the EO/SAR extension is that they are common to each item but you are right; in reality the implementation isn't that simple and would probably increase complexity.

> If it abstracts raster things, why not call it `raster`?

I think `raster` is too generalized.  The purpose of a `sat` extension (or something similar) is to abstract the properties related to the platform (such as LS8, Sentinel1/2 etc.) to their own extension whereas `raster` has a much broader definition.  If there is a `raster`, `eo`, and `proj` spec it isn't intuitive where specific properties are (ex. EPSG could logically be stored in all three).

> I don't think many of the sat fields you mention would be exclusive for satellites, but would also apply for aerial or drone.

When I last commented I was on the fence between  multiple extensions (`sat`, `aerial`, and `drone`) or a single platform-level extension for describing those fields with a `type` property indicating if the platform is sat/aerial/drone.  I think a single extension is better because, as you mention, they do share a lot of common fields.

**Comment by cholmes** [comment]
Moving this to 0.9.0. I think it's one of the if not the major issue to discussion for the next release, but let's not try to rush it out for 0.8.0

**Comment by m-mohr** [comment]
Related PRs: #644, #639
