### ISSUE TITLE
Question on Uniqueness of Catalog ID's

### ISSUE THREAD

**Issue by brianbancroft** [radiantearth/stac-spec#365]
Hi there, this is a quick question:

For [ID's in a collection](https://github.com/radiantearth/stac-spec/blob/v0.6.0/collection-spec/collection-spec.md#collection-fields), they are intended to be unique. Same with [items](https://github.com/radiantearth/stac-spec/blob/v0.6.0/item-spec/item-spec.md#item-fields). 

But for [catalogs](https://github.com/radiantearth/stac-spec/blob/v0.6.0/catalog-spec/catalog-spec.md#catalog-fields), this appears not to be the case. 

Is this intentional? 

Thanks. Any answer will go towards building a node-based validator.

**Comment by m-mohr** [comment]
To my understanding, Items are not strictly required to have a unique ID. Only collections are expected to be unique and I designed them this way due to the fact that these IDs are used in the WFS3 URLs such as `GET /collections/{collectionID}`. This works obviously only for unique IDs. The response is always a collection therefore it is required for collections, but not yet necessary for catalogs. It would be useful, but is not strictly required. Same applies for IDs. They need to be unique across a collection, but not necessarily globally unique. The endpoint here is `GET /collections/{collectionID}/items/{itemID}`. That's a very API centric view, but until now it's the only real constraint for the IDs that derived from inside the STAC specification itself.

**Comment by brianbancroft** [comment]
Thanks! If this is the consensus among the Collaborators, I'd be happy to see this issue closed.

**Comment by m-mohr** [comment]
Maybe let @cholmes or any of the others collaborators confirm it by closing this issue. ;-)

**Comment by matthewhanson** [comment]
I concur with @m-mohr, collection IDs should be unique, and item IDs should be unique within a collection, or else it wouldn't work with a dynamic API.

However, for static catalogs there really isn't a requirement that any of them are unique. Catalogs, especially sub-catalogs, are not unique in the Landsat catalog right now. These two catalogs both have an ID of 41. One is row 41 in path 180, and the other is row 41 in path 179. 

http://landsat-stac.s3.amazonaws.com/landsat-8-l1/180/41/catalog.json
http://landsat-stac.s3.amazonaws.com/landsat-8-l1/179/41/catalog.json

The catalogs each have a unique *path*, but not necessarily an ID (although maybe in this case I should update the ID to be path-row).

When a static catalog is ingested into a dynamic API, those sub-catalogs are ignored, at least they are in [sat-api](https://github.com/sat-utils/sat-api/tree/develop). Only Collections and Items are ingested so there is no conflict with non-unique IDs.

**Comment by brianbancroft** [comment]
Thanks!

**Comment by cholmes** [comment]
Concur - collection ID's should be unique, but catalogs I think as like 'folders' - no use case I can think of to make them unique. 

Psyched for your work on a node-based validator @brianbancroft !
