### ISSUE TITLE
Add `collection` property field

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#384]
In the `commons` extension:
https://github.com/radiantearth/stac-spec/tree/master/extensions/commons

it mentions having a `collections` property containing the ID of the collection the `Item` belongs to, but this is not part of core, but probably should be.

In any catalog that has multiple collections, perhaps one of the most useful properties to search on would be the collection, because full featured searching is not available at the Collection's Items endpoint: /collections/<cid>/items/, and it would only appear under the Items links which is awkward and not available for searching.

Since Items are not strictly required to be part of a collection it should be optional, but if it is in a collection this field should be provided.

**Comment by m-mohr** [comment]
I don't quite get why this needs to be moved to core and can't reside in the extension?

**Comment by matthewhanson** [comment]
The reason is that the ability to search Items within a Collection has nothing to do with whether or not the `Commons` extension is used.  Collections are core, but being able to search for items within a collection with any of the `query` terms is currently not possible. You could be using no extensions at all, but you might have 50 Collections and no way to do a complex query on Items within one of them.

**Comment by m-mohr** [comment]
Thanks. 

By the way, is a collection field (which is common across all items of a collection) put into the collection properties? Or does it reside in Items, which would somehow be a special behavior?

**Comment by matthewhanson** [comment]
Well for sat-api there is a collection property in both the Collection and the Item, so I guess it is special behavior because it applies to all Items, but stays in the Items.  Based on implementation it might not have to be that way, but if it was not in the Item I think it might make search implementation harder.

On a related note, we recently changed the behavior of sat-api, but will open up new ticket about that.

**Comment by mojodna** [comment]
When figuring out how to display collection information, I was asking myself whether the `collection` property duplicates the link with `rel=collection` or if it has an additional purpose...

The conclusion I came to was that it duplicates the link (with less information), so I was inclined to use the link to populate the UI (especially since it came with a URL to point to for navigation purposes) and ignore the `collection` property.

>  it would only appear under the Items links which is awkward and not available for searching.

This is when items are indexed as-is, correct? If some mild post-processing occurred (surfacing the link), this would be less problematic?

**Comment by matthewhanson** [comment]
@mojodna There are two main problems:

1 - API spec currently doesn't allow for searching of non properties, so there's no way to search for items by collection if there's no collection property
2 - The collection ID doesn't appear in the link info, you have to follow the link to get the true ID of the collection, so this seems it would make searching by collection ID even harder.

So if we added an additional query parameter to search by collection, and the implementors indexed the true collection ID for each item then that would be ok, but all that seems much more difficult than having it as a property of the Item

**Comment by mojodna** [comment]
Ah, the API. I was looking through a different lens.

FWIW, some providers appear to be including an `id` property on the link.

**Comment by m-mohr** [comment]
The only concern I have is that we need some special handling for this as with the commons extension it would usually be moved back to the collection and shouldn't stay in the item by default. AT least I couldn't find any info in the commons extension that this property is handled differently than any other property. But moving it back to the collection doesn't make any sense as then you have the idea in the collection twice. So maybe that's even a badly documented feature which needs a fix in 0.6.2. Or we move collection somewhere differently and add an API parameter as alternative. Don't think that's such a bad option in comparison to define an exception in the commons extension.

**Comment by matthewhanson** [comment]
@m-mohr I agree the exception isn't that great. I had always been thinking of the collection property in the Item and Collection as basically a foreign key, but you are right it doesn't fit into the spec at all.

So I'd be fine with a new Collection parameter in the API, and as long as the collection link was required to have the collection ID that would be sufficient, it's definitely important to have the collection ID appear somewhere in the Item without having to follow the Collection link.

**Comment by joshfix** [comment]
I really like the idea of having a collection parameter for the API.  I also agree that it's important to have the collection ID appear somewhere in the item.  I don't necessarily like the idea of needing to loop through every link, then either parse it out of the path or look for the "id" field (which is a non-standard link attribute) in order to get it.  

My implementation uses the collection value (I currently implement it in item properties just like @matthewhanson) on a per-item basis for a variety of functionality.  I think it would be great to have in the core as an optional field, but I'd be fine if it were available in an extension.

I couldn't find where there was any requirement or expected default behavior to move common properties into the collection.  My understanding is that the commons extension is there simply as an option if you had a common field and you wanted to avoid duplication.  Admittedly it would be weird if you implemented the collection field in item properties _AND_ moved it into the collection, as @m-mohr mentioned.  

It's a shame there isn't a common field for the collection that could be shared between the collection itself and the item.  Without sidetracking this conversation, IMHO it would be cool to extend the definition of the commons extension to be able to move items bidirectionally between item properties and collections, so you could do things like include the license in every item if you so desired (or in this case, the collection id).  I suppose that idea is moot without having a common field, however.

**Comment by m-mohr** [comment]
To avoid exceptions in the commons extension and to make implementations easier as by default the the collection field would also be moved to the collection, it would be logical to move the collection field from properties one level up so that it is on the same level as bbox, id, properties, links etc. Does that sound good to you all as well?

> I couldn't find where there was any requirement or expected default behavior to move common properties into the collection.

It's optional, but if I'd implement it I would just automatically move everything that is common to collections, which the collection field would be. But that's more an implementation issue than a spec issue. So spec-wise we are all fine...

> It's a shame there isn't a common field for the collection that could be shared between the collection itself and the item. Without sidetracking this conversation, IMHO it would be cool to extend the definition of the commons extension to be able to move items bidirectionally between item properties and collections, so you could do things like include the license in every item if you so desired (or in this case, the collection id). I suppose that idea is moot without having a common field, however.

That's something we were talking about under the term "common metadata model", but we never finished the discussions, but I wouldn't put it into a commons field as moving core collection fields around would mess things up. It wouldn't be clear where to look for the data. As there is no (GeoJSON) structure around the collection as in the Items we could just put everything top-level, I guess? Anyway, there are some related issues: #385 (Single file items), #392 (Make Commons Extension core)
If you'd just like the license in the item, you can use the Single Item Extension "workaround" by the way.

**Comment by joshfix** [comment]
> To avoid exceptions in the commons extension and to make implementations easier as by default the the collection field would also be moved to the collection, it would be logical to move the collection field from properties one level up so that it is on the same level as bbox, id, properties, links etc. Does that sound good to you all as well?

That sounds fantastic to me.

I guess my idea wasn't "moving" collection fields **out** of collections and into items, but was optionally duplicating collection fields into items.  Literally the commons extension in reverse, if so desired.  You'd always know you could find what you're looking for in the collection.  But ya, none of that matters without the collection being a common field and not having a common metadata model.

For now, I would be thrilled to officially have "collection" anywhere that I can simply select it.  I would definitely be satisfied having it in the root.

**Comment by m-mohr** [comment]
Hmm, currently the commons extension doesn't allow having fields in an item that are available in an collection (generally, this also applies for eo, sar and other fields). Can't exactly remember the good reason we had for that, but probably something like: always having a single source of truth and easier merging as no conflicts can appear.

**Comment by m-mohr** [comment]
I'm thinking whether it could be a good idea to move the collection field one level up to the root of the item. It would make the Commons extension a bit easier to use as you don't need special treatment for collection, which should not be merged with collection properties. Just feels cleaner overall.

**Comment by joshfix** [comment]
I'm 100% on board with this.  Only question is, would it be mandatory or optional?

**Comment by matthewhanson** [comment]
:+1: moving `collection` to root and adding query parameter to API.

**Comment by m-mohr** [comment]
> I'm 100% on board with this. Only question is, would it be mandatory or optional?

I'd say required if a collection is used.

**Comment by m-mohr** [comment]
PR is open for reviews: https://github.com/radiantearth/stac-spec/pull/429

**Comment by matthewhanson** [comment]
This issue has been replaced by #384 that moves `collection` to the top-level.
