### ISSUE TITLE
Collections Linking to Collections

### ISSUE THREAD

**Issue by 60south** [radiantearth/stac-spec#424]
We're planning on hosting data assets from multiple satellite constellations, and each constellation will have multiple different satellite models, each with various instrument versions. There could be a lot of permutations, each with its own STAC Collection.

In the Collection examples I've looked at, they all lump the entirety of the Collection metadata into a single STAC Collection file. If something significant changes (e.g., contact info, links, licensing, etc.) that would necessitate revising all the existing Collection files. This would be a headache.

Instead, we're looking at linking to higher-level STAC Collections within Collections. For example, a data asset's STAC Item would refer to a _Instrument_ Collection that describes the source instrument; this, in turn, would reference a _Satellite_ Collection describing the platform, and so on. If something changes at, say, the mission level, only the _Mission_ Collection content would need to change and everything else stays the same.

I'm new to STAC so I'm not totally sure if this matches the intent of STAC Collections, but it seems logical. Comments? Any examples of someone else doing something similar?

**Comment by m-mohr** [comment]
In general, it is allowed to link STAC Collections from STAC Collections. Nevertheless, we haven't yet specified such an inheritance behaviour and expect that metadata is repeated in every Collection. Indeed, this leads to what you described, but makes reading full data for Collections and Items much easier. Creating the Catalog is more work, especially once things change like contact data or so. I'm not sure how many Collections you plan to have, but is it really so much work to update them?

**Comment by cholmes** [comment]
Sounds like an awesome use of STAC @60south! 

I have not seen any STAC implementations trying to do what you're describing, though OpenEO may be wrestling with some of this as they have a lot of collection. I don't think it was something we were imagining with collections, though it does kind of echo what we did with the 'commons' extension - https://github.com/radiantearth/stac-spec/tree/master/extensions/commons That lets an item specify common elements at the collection level. This would be a mechanism for a collection to specify its common elements one level up. 

I'd say that an extension on this would certainly be welcome. That's generally our path to get something in the spec - make an extension and share it with others and as it gets used more we can incorporate it into the main spec. 

I would be curious to see how these collections look in practice though. Any chance you could share some real-world examples of how you were starting to map it out? Like why does each instrument need a collection? Do they have different contact info, licensing, etc? Could you just have all instruments use the same collection? At Planet we have hundreds of satellites, a few different instruments, and 3 different constellations. I think I'd just end up with 3 'collections', and likely could group them all into one collection if needed. 

I guess the other question for me is how often will the collection level stuff change? 

I ask these because I do think it'd add complexity to client tooling to have to know to resolve information in different places, and indeed for people looking at it to know to follow a link as a collection may not have all that they need. So I lean slightly towards just repeating some information, and deal with changing a few files if there are changes. But in my mind there wouldn't be much reason to change the collection information, but I'm potentially just missing the use case.

...

Looks like @m-mohr sounded in with similar thoughts while I was writing, but I'll just go ahead and post this too.

**Comment by matthewhanson** [comment]
Agree with the points above. We had talked about the possibility of multiple inheritance when we first started talking about collections. For instance you may have a Landsat collection, but then that contains separate collections of Landsat 4, 5, 7, and 8. The hierarchy makes logical sense because it's how we subdivide and organize these things in the real world.  All the landsat sensors have certain things in common. Landsat 4 and 5 have the same sensor so it would be nice to point to the same instrument for those two datasets.

In practice however things get ugly when trying to implement this, because one record now may have to read in multiple files to get a complete record. A dynamic API could be created to probably handle this pretty well, but for a static catalog this could be really inefficient.

My sense is that repeating some of the same info across collections isn't a huge problem, because we typically don't have that many collections. The major benefit of the `commons` extension is to be able to move metadata out of all those items into the collection, but I don't see nearly as much a benefit as adding additional levels.

But it would be good to see some concrete examples of what you guys are working with @60south

**Comment by m-mohr** [comment]
Is there anything to do for us or should we close due to inactivity / question answered? @60south
