### ISSUE TITLE
Allow mixing different STAC versions

### ISSUE THREAD

**Issue by vmx** [radiantearth/stac-spec#439]
The current STAC Catalog Spec [forbids having sub-catalogs with a different version](https://github.com/radiantearth/stac-spec/blob/4053b834204ca339701f9866ccb37b0609005995/catalog-spec/catalog-spec.md#catalog-fields):

> Child Catalogs and child Collections MUST NOT specify a different STAC version

This was introduced and discussed at https://github.com/radiantearth/stac-spec/pull/268.

It is also possible to link to someone else's catalog:

> Thus a published root catalog might be a sub-catalog of someone else's structure.

There you don't have control the version of the catalog. Hence a link to the other catalog might make my own catalog not conforming to the spec if its version changes.

Hence I propose changing the sentence from "MUST NOT" to "SHOULD NOT" with a note that catalogs under your control should have the same version, external ones would be the exception (and the reason for not being a "MUST NOT". I expected that we use the definition of these terms as defined by [RFC 2119](https://www.ietf.org/rfc/rfc2119).

PS: I'm totally new to STAC, so it could well be that I'm missing something :)

**Comment by matthewhanson** [comment]
@vmx 
I think this is a reasonable requirement to relax. I can also see a provider that might eventually have a lot of different collections of historical data (e.g., a drone operator), where you create the collection and items for that mission, but then have a catalog containing all of your collections. It may not be worth it to have to update all those older collections if that STAC version does what you need it to. I think this is OK for static catalogs.

On the other hand, a STAC API is a different story. Because STAC versions might change the API, you really need to have all the collections in the catalog be the same version. *Perhaps* changes in patch version would be ok (e.g., 0.6.x), but this should also be discouraged.

**Comment by m-mohr** [comment]
I agree with @matthewhanson. For APIs it is probably good to stich with a single version and I'd guess quite easy to implement. For static catalogs this is a different story.

This restriction is mainly there to avoid clients running into problems. If you have a 0.4 (static) catalog mixed with 0.6 you'll very likely run into problems when reading it with STAC Browser and other clients. This could only be solved by implementing all versions in client software. I think this was the fear that made us adding the restriction. We'll find out in the long run whether that's something that's practically working or not and therefore get's removed or not. So I'd say leave this issue open and revisit in some time to check existing implementations etc.

**Comment by cholmes** [comment]
Agreed with the other comments. Also I don't think we yet have examples of using a sub-catalog of someone else's structure, so I'm less clear if we should call that out in the spec.

That said, a shift from MUST NOT to SHOULD NOT seems totally reasonable.

**Comment by m-mohr** [comment]
I'll make a PR for 0.8.

**Comment by m-mohr** [comment]
Changes are part of the massive PR #531.

**Comment by m-mohr** [comment]
Merged to dev, will be part of 0.8.0. We should still add recommendations about this in the best practices. Follow-up issue is #546.
