### ISSUE TITLE
label extension: Clarify requirements around Link "label:assets" property

### ISSUE THREAD

**Issue by lossyrob** [radiantearth/stac-spec#574]
[This section](https://github.com/radiantearth/stac-spec/blob/4e7aca333f663b8e6ae068ba2ecb661bcee7185a/extensions/label/README.md#links-source-imagery) of the label extension spec specifies that:

> ... the link has a new Label specific field:
> 
> | element         | type info       | name                       | description       |
> |-----------------|-----------------|----------------------------|--------------------------------------------------------------------------------------------------|
> | label:assets    | [string]        | Assets                     | The keys for the assets to which the label applies |
> 

This is useful for LabelItems with multiple "label" assets that apply to different source imagery so that the linked source imagery can be tied to the label asset that was generated from that source.

However, for LabelItems that only supply one label asset, this seems extraneous. There is not a statement of whether or not this additional link-level information is required or optional; this should be clarified in the spec.

**Comment by lossyrob** [comment]
Ah - I think I understand what this is for now. The assets in the "label:assets" property of the source Link should describe the asset _in the source Item_ to which the labels of the label Item apply to.

If that's the right read, I'm happy to clarify the docs.

The requirement component is still an outstanding question though...should this be a requirement of all source Links? Or only apply in situations where a source Item contains assets in which the labels do not apply? Perhaps it should be "STRONGLY RECOMMENDED."?

**Comment by matthewhanson** [comment]
You got it right, a link with `rel=source` is the STAC Item from which all these labels were created from, and you could of course have multiple source links. 

I was confused as well because I was looking at the SpaceNet examples, where the `source` links are pointing directly to a TIF, but they instead need to point to an Item.   So we either need to create an Item for the source imagery (if there is source imagery beyond the rendered one included with the Label Item, or we should remove those source links.   @nrweir I think your intention was to have a separate catalog for the SpaceNet imagery, was that right?

**Comment by nrweir** [comment]
@matthewhanson thats correct. I'm just finishing up reorganizing all of the SpaceNet data and making COGs where they're missing - once I'm done I'll build the new catalog.

**Comment by cholmes** [comment]
This looks merged.
