### ISSUE TITLE
Search Extension review

### ISSUE THREAD

**Issue by tomkralidis** [radiantearth/stac-spec#592]
As discussed on Gitter, we should review the rationale for the Search Extension given OGC API - Features now provides similar capabilities.

**Comment by matthewhanson** [comment]
@tomkralidis 
I see numberMatched and numberReturned here: https://github.com/opengeospatial/ogcapi-features/tree/master/core/openapi/schemas

One issue is that STAC is snake_case and OGC API uses camelCase. It hasn't really come up before because so far everything has been 1 word.  I would prefer `matched` and `returned` or other 1 word alternatives.

**Comment by m-mohr** [comment]
Fully agree with @matthewhanson, but I doubt we can change it and need to live with casing inconsistencies as WFS has been released already.

Is there anything to do for STAC 0.8? Like should we add numberMatched and numberReturned in responses to be fully compliant with OAF?

**Comment by tomkralidis** [comment]
If STAC (API) is seen as a WFS extension, then do we assume that `numberMatched` and `numberReturned` are already part of same?

**Comment by m-mohr** [comment]
I just checked it and STAC API inherits numberMatched and numberReturned from WFS just fine. So currently, things are duplicated in STAC API and we can think about the next steps during the sprint.
