### ISSUE TITLE
Proposed SAR changes

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#619]
I've been working with SAR recently and some things have come up WRT the `sar` extension.

- `sar:pass_direction` is required, but it is specific to satellites, and a SAR instrument could be mounted on an airborne platform  (which is why we need `sat` extension)
- sar:bands -> data_type: polarizations can be represented as different products (i.e., assets) within the same collection. If I have SLC and GRD products for HH and HV in the same collection I would need 4 different bands rather than 2. It seems that data_type is more a property of an asset, rather than a band (also, a single asset is not going to contain different data_types)

Also, more generally, the extension seems like it includes a lot of fields that just don't fit the purpose of "search and discovery" and I wonder if some could be pruned out.   I've got some questions out to some SAR folks to get input on that.

@m-mohr

**Comment by m-mohr** [comment]
> * `sar:pass_direction` is required, but it is specific to satellites, and a SAR instrument could be mounted on an airborne platform  (which is why we need `sat` extension)

For airborne SAR you can simply set the field to null: "Direction of the orbit, either ascending, descending or **null if not relevant**."

> * sar:bands -> data_type: polarizations can be represented as different products (i.e., assets) within the same collection. If I have SLC and GRD products for HH and HV in the same collection I would need 4 different bands rather than 2. It seems that data_type is more a property of an asset, rather than a band (also, a single asset is not going to contain different data_types)

I thought that's how bands work at the moment for EO as well?! I remember the discussions about asset specific metadata and thought the solution for now is to have more bands?

> Also, more generally, the extension seems like it includes a lot of fields that just don't fit the purpose of "search and discovery" and I wonder if some could be pruned out. I've got some questions out to some SAR folks to get input on that.

Not sure whether it's really *a lot* of fields. Which one do you think about? The only fields that are not so related to search and discovery (from my not so expert perspective) are data_type and unit in the bands. And these are just really there for better understanding from a human perspective. Maybe pixel_spaing_* is one field not so relevant.

**Comment by matthewhanson** [comment]
Yeah, but if it is allowed to be `null` then why would it be required?  Why not just make all fields required, but then set them to `null` if not relevant?  To me the point of something being required is that it is relevant in all cases.  By saying that it can be set to null if not relevant you are saying that it is optional, but you must still provide a value.


There is no data type of other asset specific metadata in EO bands: https://github.com/radiantearth/stac-spec/tree/master/extensions/eo#band-object


WRT the fields, I'm not sure yet, waiting to hear back from some SAR folks, but I will create a new issue for that.

**Comment by m-mohr** [comment]
Well, if something is not defined at all you don't know whether the creator just didn't care or whether it just doesn't apply. So in that sense a required field set to null is more explicit. So I think it's still valid to require important fields and let creators decide on them. The other question is whether pass_direction is important enough. During the discussions about the SAR extension it seemed like it is important to know this information.

**Comment by matthewhanson** [comment]
Well, it can be important, but it's important in general to any satellite based sensor, but is not in the EO extension.  It seems clear to me that we need a `sat` extension. Wrapping up sar, or eo fields with fields that are specific to satellites when there are more platforms that are on airborne platforms seems like a poor choice.

I get what you mean about having it be explicit, but it's strange that this one field is like that while others are not.  I don't see this field rising to that level above other fields which seem far more important.   Now, if there were a `sat` extension than this definitely be a required field, and `null` would not be allowed.

**Comment by matthewhanson** [comment]
Ok, I've consulted some folks and gone through the rest of the fields and propose dropping these:

- platform, constellation, instrument, pass_direction, relative orbit - all moved to `sat`
- absolute_orbit - proposing to drop this, doesn't seem to be a use case
- center_wavelength.  Feedback was that the majority of folks will be using the frequency_band code and unlikely to use wavelength or frequency. "For some bands, when you go to particularly low frequency, it is good to know the center-freq because can vary in a pretty large range (this is the case for P-Band for example). If we have to keep one, for searching, I would probably keep frequency "

Additionally I think `sar:type` is not a great name, especially if we were to drop the prefix, `product_type` or just `product` seems more appropriate (it's also something I see being useful in eo and other datasets....)

Depending on if we do something with eo:bands (#656 ) we could do something similar here, to indicate which polarizations are within what asset (and there's fewer fields here so even more of a reason to just do it).

And finally, I was wondering about the inclusion of sar:polarizations, as it just seems to be redundant with the 'sar:bands' info.  Maybe because an array like that is easily searchable using `contains`, but we don't currently have a way to search into `sar:bands` (or assets for that matter).

**Comment by m-mohr** [comment]
- I think I'm fine with dropping absolute_orbit.
- Not sure about center_wavelength/frequency_band.
- We can rename type to product_type, but there should still be specific examples such as grd, slc to lead the user a little bit.
- Polarization is required and needs to be searchable, which we don't yet have a solution for if it's in bands. Also, bands is not required for SAR at the moment. I can't recall the other reasons, to be honest.

What do the original contributors to this extension think? @AlenaDostalova, @p3dro, @mrepse, @scottyhq, @jeffnaus, @hgs-msmith, @walterggit, @claxn

**Comment by claxn** [comment]
I am not familiar with the STAC SAR metadata structure, but at least I can provide some comments from my perspective:

- I agree on introducing a `sat` extension, which allows us then to separate platform from sensor properties
- I also cannot imagine a use case where `absolute_orbit` is needed. Is there any drawback of just keeping it, even when it is not often used?
- Maybe it is better to state both, a `center_frequency` (more common than `center_wavelength`, I guess) and a `frequency_band` attribute. Because only using the frequency band does not tell you anything about the actual frequency used.
- `product_type` sounds good, it must be either GRD or SLC.

**Comment by scottyhq** [comment]
Thanks @m-mohr and @matthewhanson for pushing this forward. I haven't worked with STAC since the 0.6 version, so I'm a bit behind the times. I'll try to experiment with the SAR extension this week in order to provide better feedback. In the meantime, a couple thoughts:

> I think I'm fine with dropping absolute_orbit.

I'd say people use `absolute_orbits` fairly regularly when working with SAR data, but not necessarily for searching. As an example one project I'm working on requires interferometric processing folders labeled by absolute orbit `int-15924-15749`. Sentinel-1 absolute orbits are in the file name, for example `18888` for S1B_IW_SLC__1SDV_20191112T020146_20191112T020213_018888_0239FC_2ECE. I suspect most people will search by `datetime` though and not `absolute_orbit`.


> center_wavelength. Feedback was that the majority of folks will be using the frequency_band code and unlikely to use wavelength or frequency. 

Agreed. Most satellite systems to-date fall into X, C, and L bands. Imaging a day when all sensors have STAC metadata, it would be nice to filter a search for just X-band without remembering the exact center wavelength value.

**Comment by matthewhanson** [comment]
Thanks for the feedback @scottyhq that confirms what I was thinking.

Another thought I had was about the actual utility of `sar:data_type` and `sar:units` in the `sar:bands` object, see here: https://github.com/radiantearth/stac-spec/tree/dev/extensions/sar#band-object

One is that I'm not sure what data_type and units is really providing beyond the  `sar:product` field that is given at the Item level.  Or it could be provided via a description field in the asset if we add that.  Is there a use case for how someone might search based on these terms (remembering that we currently don't have a way to filter on object types like sar:bands anyway)....or is there at least some utility in a user knowing what these are for a collection?  Or is it basically redundant with how the collection is defined anyway?

It seems like if data_type and units *are* useful in SAR, they would also be useful in EO and other types of data as well, and don't seem unique to SAR data.

**Comment by stringhamc** [comment]
@matthewhanson I've been confused by the combination of `sar:data_type`, `sar:units`, `sar:bands` and `sar:polarization` as well. I think `sar:bands` should be dropped and in place use`sar:polarizations` and instead have a polarization object. This would be different from EO, but would be less confusing to a user because there are some multi-band (ie multi-frequency) SAR instruments like SRTM, NISAR etc. The images from a multi-frequency SAR are generally separate assets because the resolution or coverage is significantly different.

As for `sar:data_type`, I would expect the types to be `complex` or `magnitude`.

from @claxn 
> product_type sounds good, it must be either GRD or SLC.

Those are the two data types for Sentinel, but there are many other product types that could be provided. For example, see [TerraSAR-X's product guide](https://www.intelligence-airbusds.com/files/pmedia/public/r459_9_20171004_tsxx-airbusds-ma-0009_tsx-productguide_i2.01.pdf). Most of the products are different by the projection geometry and the multilooking that is done, and each provider has a slightly different name for each product type. A bit more complete table may be:

| Product Type | data_type | Description |
|-------------------|----------------|----------------|
| SSC | complex | Single-look Slant-range Complex image (standard SLC) |
| MGD | amplitude | Multilooked Ground-range Detected Image (GRD in sentinel) |
| GEC | amplitude | Geocoded Ellipsoid Corrected  Image |
| GTC | amplitude | Geocoded Terrain Corrected Image |
| SGC | complex | Single-look Ground projected Complex image |

The first four products are standard products from both TerraSAR-X and Cosmo Skymed though a few of the abbreviations are different. The last one I suggest to cover SLCs that are commonly generated with time-domain methods, similar to what Howard Zebker is discussing [here](https://ieeexplore.ieee.org/document/8897959).

**Comment by stringhamc** [comment]
I definitely like the separation of the `sat` fields from `sar`, and only keeping `sar:frequency_band`. I'd also second removing `sar:absolute_orbit`. InSAR compatible images can still be found with relative orbit, so `absolute_orbit` was redundant with `datetime` and `relative_orbit`.

**Comment by stringhamc** [comment]
It would be useful to get someone from NISAR's perspective... @piyushrpt?

**Comment by piyushrpt** [comment]
I'm not very familiar with the STAC SAR spec but here are some use cases for NISAR which we have found hard to find support for in publicly available SAR specs:

1. Support for contemporaneous multi-frequency acquisitions - S-SAR / L-SAR operating together. This is would be equivalent to having data from two sensors in the same product. It might be ok to treat this data as two different products to keep things simple. 

2. Support for two frequency bands from the same sensor - L-SAR can possibly operate in imaging modes with two bands like dual-frequency GPS to allow for interferometric ionospheric phase screen corrections. This is not equivalent to polarization as each of the two bands can operate in different polarization combinations. 

3. NISAR plans to standardize some other products like polarimetric covariance and unwrapped interferograms - see Products section of https://nisar.jpl.nasa.gov/files/nisar/NISAR%20FINAL%209-6-19.pdf

4. They are also looking into incorporating Cycle number just like track / frame number for easier representation of interferograms. Community currently uses two date combinations with relative orbit and frame number. If all products are generated on a predefined path-row (Track-frame) scheme using cycle number will simplify naming interferograms. Since, this is hard to generalize across missions / sensors - maybe its worth considering a unique mission ID (cyclenum-tracknum-framenum for NISAR or relativeorbit-uniqueburstid for Sentinel-1 etc)

5. Swath widths depend on the mode and in case of polar regions - due to frequent repeats one may choose to operate the instrument with smaller swath width to keep data volumes down. A field that specifies extent/ area might be useful? This could also be derived from spatial bounding box if that information is already available. 

Having looked at the schema for the SAR spec in the repo here, there are a few more things that could be relevant:

1. There is no representation of swaths / bursts. This might become important if someone decides to repackage SLC data from sensors like Sentinel-1 into COGs containing individual bursts. How would collection of these be represented? As individual products or a collection? I think this question reflects my unfamiliarity with the spec.

**Comment by matthewhanson** [comment]
This is some very useful feedback @stringhamc and @piyushrpt , thanks.

To the points @piyushrpt raised:

1. The easiest thing to do right now, without changes to the spec, is yes to keep those two different acquisitions as different STAC Items. Both could appear within a single Collection as each Item could specify the instrument, frequency_band, and center_frequency used for those assets. However, this does support the idea of more options to have asset specific metadata.

2. If a single collect (scene) uses a single frequency, then this would be a single STAC Item and it would specify the center_frequency used.

3. standardized products are good, it can help us define a set of values in the future. For now, a NISAR collection can specify the set of products at the Collection level.

4. The newly added `instrument` extension adds a `mission` field which could be used for this.

5. Each Item has a bbox and a geometry, so I think that handles this.

6. Representation of swaths/bursts.  Would each of the bursts (e.g., COGs) have different bounding boxes/geometries?   I think that's true, in which case I'm not sure. The geometry of a single STAC Item should be the region of data covered by the assets. If a single asset contains only a subset of that it seems a bit strange, but I'm not sure it goes against the spec.  The alternative would be to make each swath/burst it's own Item, which seems less than ideal as it would make it more difficult to use them as a set together.

**Comment by matthewhanson** [comment]
Regarding the feedback from @stringhamc,

since `product` determines `data_type` and `units`, I would propose dropping those fields as well.  So in summary, I would now propose to:

- drop `sar:absolute_orbit`
- drop `sar:center_wavelength`
- drop `sar:data_type` and `sar:units` from the `sar:bands` object

We might further discuss bands and polarizations, but if the above is agreed on I can issue a PR for those.

**Comment by stringhamc** [comment]
@matthewhanson sounds good to me.
