### ISSUE TITLE
EO: gsd -> resolution

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#672]
A thought from the working session:
Should we rename gsd to resolution?

I think that makes it easier to understand, so +1.

cc @matthewhanson

**Comment by matthewhanson** [comment]
I originally pushed for GSD (Ground Sample Distance) as a way to be explicit about what the term is.

In digital cameras resolution is often given "Pixel Resolution", as total pixels in x and y (e.g., 10,000 x 8,000).

Sometime sensors specify "Spatial Resolution" (such as in medican imaging and with scanners) and is given as pixels-per-inch (ppi), or more generally pixels-per-some-unit

For optics, resolution is given in terms of angular separation. 

In remote sensing, resolution is usually provided in terms of Ground Sample Distance, or the distance on the ground between two adjacent pixel centers.

However, if we provide `resolution`, since we specify the units are to be in meters, I don't think there's any confusion what's being referred to and is clearer than gsd.

So +1 from me.

**Comment by jbants** [comment]
I'd prefer to leave it as GSD as resolution can mean many different things like Matt was suggesting. Another "resolution" example would be "spectral resolution" where we look at the resolving power of a band to identify features in the EM spectrum. 

Leaving it as GSD is specific enough not to cause confusion with the other resolution types.

-1 for me

**Comment by m-mohr** [comment]
Telco: Agreed to not rename it.

**Comment by m-mohr** [comment]
From @jlaura:

> Here’s a legit medium article trying to help folks differentiate between GSD / resolution, etc. I suspect most non-geospatial nerds make this distinction? I know planetary scientists out of many labs do not.
> 
> https://medium.com/sentinel-hub/the-most-misunderstood-words-in-earth-observation-d0106adbe4b0
