### ISSUE TITLE
Remove API checklist item from issue template

### ISSUE THREAD

**Issue by matthewhanson** [radiantearth/stac-spec#749]
With API spec moved to new repo, this can be removed from the issue template (and should probably be added into https://github.com/radiantearth/stac-api-spec issue template)

**Comment by m-mohr** [comment]
Not 100% sure about this, I think there should still be a reference to API spec. How do we ensure that the API always catches up with recent changes in the "core" spec (e.g. update collection fields or so)?

**Comment by cholmes** [comment]
Sorry, made the PR before I saw @m-mohr's comment. But this is just the line in the template that says 'I have run `npm run generate-all` to generate the files'. 

I could see how we may want to use PR templates to help make sure people are updating the api spec. But I also could see that its the responsibility of the api spec to update fields / examples when it does a release. And it can choose the stac core version it wants to depend on, and may even skip a minor version. Like stac-api-spec 1.0.1 might depend on stac-spec 1.0.5, since it was just a lot of minor changes that didn't really matter to the api.

I think the api spec needs to declare what version of core it depends on, and then part of its release process needs to be to update all its openapi / examples to align.
