### ISSUE TITLE
Collection-level assets

### ISSUE THREAD

**Issue by m-mohr** [radiantearth/stac-spec#779]
This issue is to capture some ideas, thoughts and related issues on collection-level assets. This came up several times in the past and we should document our thoughts and decisions.

Recently, collection-level assets came up in the following issues:
* #713: How to expose ZARR data?
* #778: How to expose collection thumbnails?
* #614: How to expose tiled assets? (There it was decided to go for a single item, but collection-level was also an option, but STAC had no option for collection-level assets).

A related extension is the "asset" extension for Collections. It allows to specify assets exposed in Items, but misses the actual link (`href`). Issue #661 asks for promoting this extension to Core. 

One idea I have is based on my similar ideas in #713 and #778: We could extend the `asset` property from the asset extension so that it optionally allows to have a `href`. If there's a href, it's a collection-level asset. Otherwise clients can assume that there's an item-level asset...

What do you think?

cc @cholmes @matthewhanson

**Comment by matthewhanson** [comment]
Overall I agree that having Collection level assets could be useful.  I think thumbnails are a valid use case here, as are Zarr or other similar types of formats that represent a large collection of data spanning a very large region (such as the whole global) that are traditionally represented as individual tiled files.

However, I think the `asset` extension is clearly a different thing entirely.  The asset extension is for indicating the types of assets that can be expected in member items, whereas these are assets for the entire collection.

What if you have a collection with Items and use both the asset extension as defined, but also a collection level asset?  Is it just that one of the assets has an href?

One possibility is to treat Collection level assets the same as for Items (so under an `asset` field), but change the asset definition to something else that clearly indicates that it is a definition of assets rather than assets themselves.

**Comment by m-mohr** [comment]
@cholmes @matthewhanson So how do we proceed regarding the Zarr dicussion and upcoming mini-sprint? All my examples and thoughts went towards collection-level assets and I still think that's a good idea. If you think it's better going forward with Items, you should propose a new example and we should also start doing PRs for whatever needs to be changed (datetime changes?) or at least make a list of ToDos. Otherwise we don't haven't good a good basis for the mini-sprint and I really don't want to discuss these things there.

**Comment by cholmes** [comment]
Hrm. I think it's probably just best to proceed with collection-level assets. I'm comfortable with an extension that does collection level assets, and that could help with making the case for them in the core. Zarr is the most compelling real case I've heard for collection assets, though I still don't understand exactly what is most useful. We have a future item to investigate zarr at item level. Perhaps when we do that the collection level assets make less sense / we propose another way to model assets. Or the other way many others make use of collection level assets and the case is clear. 

I am +1 on treating collection level assets the same as items, and changing the name of the asset definition. I think that was what I found most confusing in the example - that asset includes actual things (collection) and definition. I think I had always thought the asset definition would be named something like 'asset-definition'. If we want to do collection level assets I think it should exactly reflect the item level ones.

**Comment by m-mohr** [comment]
Okay, that sounds good to me although I'm not sure we really change all that much later on once things are implemented in 1.0...

So then `asset_summaries`? ;-)
