### ISSUE TITLE
datetime properties field needs clarification 

### ISSUE THREAD

**Issue by joshfix** [radiantearth/stac-spec#837]
Item spec states that the “datetime” properties field is a required field, and that additional fields exist: 

https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#properties-object 

However, when following through to the STAC Common Metadata link under additional fields, “datetime” shows up as under “Date and Time” and appears to be defined as an optional/additional field? 

https://github.com/radiantearth/stac-spec/blob/master/item-spec/common-metadata.md#date-and-time

**Comment by m-mohr** [comment]
Yeah, that's a bit confusing due to the nature that common metadata fields are meant to be universally usable (e.g. in assets and item properties) and you can pick what you need. Due to it being allowed in assets, it's not possible to make "requirements" there. I tried to solve this by referring to the Item spec where you see it's required in Item properties.

**Comment by m-mohr** [comment]
PR is up at #859
