### ISSUE TITLE
View Geometry Extension proposal: add the solar exoatmospheric spectral irradiances

### ISSUE THREAD

**Issue by fabricebrito** [radiantearth/stac-spec#852]
Hello, 

The View Geometry Extension provides the **view:sun_azimuth** and **view:sun_elevation**.  (https://github.com/radiantearth/stac-spec/tree/master/extensions/view)

If we add a **view:eai** for the exoatmospheric spectral irradiances (a.k.a. ESUN in several radiance to reflectance formulas) we would have all the information to do the optical calibration reading all the info from the STAC item:

* sun azimuth
* sun elevation 
* solar exoatmospheric spectral irradiance (band-dependent)

While Landsat-8 doesn't need this info, Landsat 1-7, Kompsat-2/3/3a, SPOT-6/7, CBERS-4, Gaofen-1 (just to name a few) would certainly benefit from this.

See section "Solar exoatmospheric spectral irradiances (ESUN) for the Landsat 1-7 data" of https://www.usgs.gov/land-resources/nli/landsat/using-usgs-landsat-level-1-data-product

**Comment by cholmes** [comment]
Sounds super interesting @fabricebrito and definitely a use case I'd be excited to support. 

I think the only question for me is where to put it, as it feels a little different then the view fields, which are all about the angles.

I'm far from a remote sensing expert, so I may be grouping things wrong, but what about something like a 'calibration' extension? At Planet we have a field called 'reflectanceCoefficient' which feels in line with this, as it's another band-dependent field. Not sure that really groups under 'calibration' or not. But it does seem like there's a group of related fields related to spectral responses.

**Comment by matthewhanson** [comment]
I think the exoatmospheric solar irradiances would belong better for each band in eo:bands, since as you pointed out they are band dependent. 

@cholmes They are a little different then a reflectance coefficient. Whereas a refl coef needs to be simply applied to the band counts to get a reflectance value, the ESUN var is one of several other parameters that need to be taken into consideration (e.g. day of year to determine earth-sun distance).

However, I wonder if this information is better off in header information within the data itself? Whereas STAC does include some variables for usage rather than strictly searching, they are variables that allow users to avoid fetching the data, a potentially expensive operation. 
For calibration coefficients, you'd have to get the data anyway in order to use them. So maybe it's better off in the header?  Or perhaps a separate extended metadata spec that could be STAC-like but useful for these sorts of data usage operations.

**Comment by m-mohr** [comment]
Closed in favor of issue https://github.com/stac-extensions/view/issues/3

**Comment by emmanuelmathot** [comment]
see proposal in `eo` : https://github.com/stac-extensions/eo/pull/4
