### ISSUE TITLE
Querying static STAC by giving bounding box

### ISSUE THREAD

**Issue by Dimplejain23** [radiantearth/stac-spec#958]
How to query in static STAC by passing the bounding box and date filter. 

Given below is the directory structure i am following:-
── eo
    ├── catalog.json
    ├── landsat-8
    │   ├── collection.json
    │   └── landsat-8-l1
    │      └── item1.json
    │      └── item2.json 
    └── sentinel-2
        ├── collection.json
        └── sentinel-2a
            └── item1.json
            └── item2.json

@m-mohr @cholmes @matthewhanson

**Comment by m-mohr** [comment]
Welcome to STAC @Dimplejain23.

A static catalog can't be queried. It's just a set of files and you need a program to crawl and ingest them so that the program can build an index you can search on. There's probably something on STAC Index, which you could use for that. See https://stacindex.org/ecosystem
